### ISSUE TITLE
respect loop mark when playing back mod files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#160]
```
Eliuk reports an issue with mod playback:

mod format has a loop mark.
if glk loops a mod, should respect the loop mark
garglk doesn't respect the loop mark in mods.
and loops all track, from begining.

(not all mods have a loop mark)
```

Original issue reported on code.google.com by `bcressey@gmail.com` on 8 Sep 2011 at 10:04

**Comment by cspiegel** [comment]
The Blorb specification doesn't mention looping in modules (nor in AIFF/Vorbis files), so at the very least it's undefined/unspecified behavior. It's not clear what it'd mean for looping in MOD files, so I'm going to close this. Unless the Blorb and/or Glk specifications are updated to deal with more nuanced looping, Gargoyle will ignore loop markers in files, and rely on authors who want looping to manually implement it.
