### ISSUE TITLE
Problem with Danish special letters

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#187]
```
What steps will reproduce the problem?
Loading a danish AGT game (in my case "Oprør på Nyx")

What is the expected output? What do you see instead?
The letters Øø is shown as ¥¢

What version of the product are you using? On what operating system?
Gargoyle build 2011.1
AGiliTy 1.1.1.1

Please provide any additional information below.
The Danish alphabet contains the special letters Æ/æ, Ø/ø and Å/å.
Æ and Å are showing correctly, but not Ø
```

Original issue reported on code.google.com by `TorbenBo...@gmail.com` on 11 May 2012 at 9:46

**Comment by cspiegel** [comment]
Probably still an issue, but no link to the game was ever provided and Google isn't finding it.  I'm willing to look into AGT character set handling if I can find a game that exhibits this behavior.

If AGT games don't specify their encoding, however, it'd be a tricky task.
