### ISSUE TITLE
RFE: Quicksave and quickload for gargoyle free.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#194]
```
Would be nice have, as in many emulators.

FKey for saving, FKey for loading, FKey for cycling.

Saving moves the saving pointer forward, circular list.

Problem is, where emulators can have a nice image to identify the save, IF only 
has text. Also save the buffer and display it as a image or overlay when you 
cycle?

Also, needs neutral location for the saves (probably someplace in ~).
```

Original issue reported on code.google.com by `i30817@gmail.com` on 31 Oct 2012 at 2:10

**Comment by cspiegel** [comment]
This is an interpreter issue, and while Gargoyle does "maintain" some old interpreters out of necessity, this isn't something that can realistically be part of Gargoyle (I mean, it can, but it'd be a _lot_ of work to do it and maintain it).

In short, while it could be done, I don't consider it Gargoyle's place.

That being said, Bocfel has some convenience functionality for saving: `/ps` to do a quick save, `/pop` to do a quick load, `/ls` to list saves (see `/help` for more).  These are in-memory, but the next release of Gargoyle will include autosave functionality in Bocfel as well.  A combination of these should at least somewhat mitigate save/restore problems, at least in Z-machine games.
