### ISSUE TITLE
Desktop file on the debian package doesn't allow showing gargoyle-free in file association

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#196]
```
This may be because i'm using the ubuntu repository version. Here is the 
contents of the desktop file:

[Desktop Entry]
Name=Gargoyle-Free
Exec=cautious-launcher %f gargoyle-free
NoDisplay=true
Terminal=false
Type=Application
Icon=gargoyle-house
MimeType=application/gam;

It needed
NoDisplay=false
or erasing that line maybe.

This is very bad because taf and other IF files are not associating with 
nothing by default.
```

Original issue reported on code.google.com by `i30817@gmail.com` on 27 Nov 2012 at 2:46

**Comment by a-detiste** [comment]
`cautious-launcher` is a Ubuntu-only thing
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=608342

The Debian package currently doesn't have the `MimeType=application/gam` at all

**Comment by cspiegel** [comment]
Gargoyle now includes a working desktop file.  It's up to packagers to make sure it's properly installed.
