### ISSUE TITLE
Increase undoSize for Git

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#199]
```
See discussion on mailing list:
https://groups.google.com/d/topic/garglk-dev/T1vhhm5geNs/discussion

undoSize needs to be tuned above 512 KB.
```

Original issue reported on code.google.com by `bcressey@gmail.com` on 30 Dec 2012 at 10:44

**Comment by cspiegel** [comment]
This was increase as of git 1.3.3, from 512KB to 2MB.  I tested Emily Short's *Counterfeit Monkey*, a guess as to the game referred to in the mailing list, and undo worked with 1.3.3, while it failed on the last official Gargoyle release.  At the very least the increased undoSize was sufficient in this case.

If there are any other games which failed previously but still fail with the updated buffer, I'd like to know, and I'll bump it more.  I'm keeping this ticket open for the time being while I explore it further, but will close it if I can't find any failures with the current code.

**Comment by cspiegel** [comment]
I've found no problems, so I'm closing this as fixed.
