### ISSUE TITLE
TADS 3 interpreter out of date

### ISSUE THREAD

**Issue by GoogleCodeExporter** [garglk/garglk#203]
```
The TADS 3 VM included with Gargoyle is very outdated now. The last stable 
release, 2011.1, uses 3.0.18 and even the latest source code in the repository 
is only 3.1.0, whereas the latest official TADS 3 release is now at 3.1.2. 
Because of the major changes and additions in recent TADS 3 releases, games 
released with newer versions of the compiler (like the newest version of my 
game, It) will no longer run on Gargoyle.
```

Original issue reported on code.google.com by `emily.bo...@gmail.com` on 16 Feb 2013 at 3:07

**Comment by cspiegel** [comment]
I just pushed a branch (called tads3) which incorporates experimental support for TADS 3.1.3.  Testing, and following that, some cleanup, will be required before I'd be comfortable getting it into master, but at the very least *It* starts up and works through a few commands, so it probably shouldn't be too much work getting it into shape.

**Comment by cspiegel** [comment]
The TADS update has been merged into master.
