### ISSUE TITLE
Build files need updating for OS X 10.9 / 10.10

### ISSUE THREAD

**Issue by mtwomey** [garglk/garglk#216]
I worked through obtaining a working binary, but I'm not completely sure how I did it. Much brew install this and that and editing of Jamrules. If someone has this worked out, please contribute - otherwise, when I get a chance, I'll try to recreate from scratch and contribute an update.

**Comment by faried** [comment]
It seems to work with [these changes](https://gist.github.com/faried/446ddd8bc4f538237d48).  I use MacPorts.

**Comment by erkyrath** [comment]
I had to figure this out on MacOS 10.12, using homebrew rather than macports. I used @faried's changes and then changed some more things. (To allow for the fact that the libs are found in *both* /usr/lib and /usr/local/lib.)

https://gist.github.com/erkyrath/a0219bcfa30dc78979e244aec23a0700

**Comment by erkyrath** [comment]
I had to revamp that script quite a bit to get a result that really worked. (On machines other than mine.) The branch that I used, with all changes, is at https://github.com/erkyrath/garglk/tree/buildbrew .

Do people want this as a PR? If so, I really should rip `gargoyle_osx.sh` out entirely and rewrite it in Python. My shell hacks are odious.

**Comment by erkyrath** [comment]
This is now covered (https://github.com/garglk/garglk/pull/254 and the PRs that went into it). Can be closed.
