### ISSUE TITLE
Nitfol

### ISSUE THREAD

**Issue by fedor1113** [garglk/garglk#218]
Hello!
I've downloaded the source code and tried to "jam install". It showed me a mistake, which was related to nitfol, so I opened nitfol folder and found that in nitfol script there was this misprint: #!/bin/ash, which (as I understand) should be #!/bin/bash

**Comment by cspiegel** [comment]
Please include the actual error message you're receiving.  While /bin/ash probably should be /bin/bash, that's in a script that's not used by Gargoyle, so it should have no effect.

I've committed another fix for Nitfol which may solve the problem you're having, but if not, please open a new issue.
