### ISSUE TITLE
Add a README file.

### ISSUE THREAD

**Issue by ccxvii** [garglk/garglk#219]
Please add a README file so that people can see on the github landing page where to go for the mailing list and where to find the downloads.

**Comment by manpages** [comment]
:+1: 

And please, even for developers, make it a little bit more informative.

Don't assume prior knowledge of what seems obvious for an IF tooling developer with years of experience.

**Comment by BroadcastGames** [comment]
I suggest the README point to the Wiki.

The Wiki build also needs to have the parts about SVN checkout from code.google removed.

**Comment by Mirppc** [comment]
The Wiki is not very informative and when you are compiling in offline mode then it is pretty useless.  I would concur about there being some form of a readme file to be included with at least some instructions for various OS's, dependencies and so forth.

**Comment by cspiegel** [comment]
I've added a basic README (adapted from the original Gargoyle site), which doesn't actually address most of the issues here (no build instructions, mailing list, etc), but I wanted to at least start by having a reasonable landing page.

I'll flesh out some Linux build instructions but I won't be able to do Windows or Mac instructions.  I'll also add pointers to various useful areas (mailing list, download links, and so on); but at least there's a base from which to work now.

**Comment by erkyrath** [comment]
Build instructions should go in the INSTALL file.

The README should direct people to https://github.com/garglk/garglk/releases for the app download. That's what most users want.

Linking to the mailing list is good, although probably only interesting to developers.

**Comment by Mirppc** [comment]
I concur,  it took me a good number of years to finally become successful in compiling Gargoyle for linux.  Pointing to the wiki is fine and dandy, unless you are taking the code to compile on a machine without an internet connection.  Having the build instructions in a INSTALL file would be useful.

**Comment by cspiegel** [comment]
README and INSTALL have existed for a while now.
