### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by akien-mga** [garglk/garglk#223]
Hi there,

I think it would be nice to tag a new release as much as happened since 2011.1. I'll try to test the current master branch to see if it's release ready, I remember having a couple issues with some interpreters a while back while testing r619 of the Google Code repo.

I may also have a couple patches to proposes in PRs based on my packaging for Mageia: http://svnweb.mageia.org/packages/cauldron/gargoyle-free/current/SPECS/gargoyle-free.spec?view=markup, I'll have to check.

**Comment by salty-horse** [comment]
Good idea!

Here's a relevant discussion from the mailing list:
https://groups.google.com/forum/#!topic/garglk-dev/RaIeXYNiivI

A few people have volunteered making builds for some of the platforms.
As mentioned, we need to go over the interpreters and update them to their latest versions.

**Comment by NULUSIOS** [comment]
Is there any progress with this?

**Comment by realnc** [comment]
> Is there any progress with this?

cspiegel is currently working out the kinks of upgrading TADS to the latest version.

**Comment by fireton** [comment]
Any progress? In fact, I really waiting for it.
