### ISSUE TITLE
Compiling pre-req missing

### ISSUE THREAD

**Issue by AndreasDavour** [garglk/garglk#224]
On a modern Fedora I ran these before I could compile without errors:

dnf install gtk2-devel freetype freetype-devel fontconfig-devel fontconfig glib-devel glib2-devel glibc-headers

Maybe some more things are needed, but I had them installed already

**Comment by AndreasDavour** [comment]
turns out it also need some thing called libgarglk.so whatever that is.

**Comment by salty-horse** [comment]
Garglk is responsible to build libgarglk, so don't worry about it. I'm closing this issue, as you have provided more details in #225.
