### ISSUE TITLE
can't link libgarglk.so

### ISSUE THREAD

**Issue by AndreasDavour** [garglk/garglk#225]
[ante@adavour garglk-stable-2011.1]$ jam install
OS is LINUX (gtk+) 
BUILD is RELEASE 
...patience...
...found 1554 target(s)...
...updating 39 target(s)...
Cc build/linux.release/garglk/imgload.o 
SharedLink build/linux.release/garglk/libgarglk.so 
/bin/ld: cannot find -lsmpeg
build/linux.release/garglk/cgfref.o: In function `glk_fileref_create_temp':
cgfref.c:(.text+0x1ef): warning: the use of `tempnam' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status

        cc -shared  -Wl,-soname,libgarglk.so -o build/linux.release/garglk/libgarglk.so build/linux.release/garglk/gi_blorb.o build/linux.release/garglk/gi_dispa.o build/linux.release/garglk/cggestal.o build/linux.release/garglk/cgblorb.o build/linux.release/garglk/cgfref.o build/linux.release/garglk/cgmisc.o build/linux.release/garglk/cgstyle.o build/linux.release/garglk/cgstream.o build/linux.release/garglk/cgunicod.o build/linux.release/garglk/cgdate.o build/linux.release/garglk/window.o build/linux.release/garglk/winblank.o build/linux.release/garglk/winpair.o build/linux.release/garglk/wingrid.o build/linux.release/garglk/wintext.o build/linux.release/garglk/wingfx.o build/linux.release/garglk/winmask.o build/linux.release/garglk/event.o build/linux.release/garglk/draw.o build/linux.release/garglk/config.o build/linux.release/garglk/imgload.o build/linux.release/garglk/imgscale.o build/linux.release/garglk/fontdata.o build/linux.release/garglk/babeldata.o build/linux.release/garglk/sndsdl.o build/linux.release/garglk/sysgtk.o build/linux.release/garglk/fontgtk.o build/linux.release/babel/babel_static.a `pkg-config freetype2 gtk+-x11-2.0 gdk-x11-2.0 gobject-2.0 glib-2.0 fontconfig --libs` -ljpeg -lpng -lz -lSDL_mixer -lSDL_sound -lSDL -lsmpeg -lvorbisfile
    
...failed SharedLink build/linux.release/garglk/libgarglk.so ...

**Comment by AndreasDavour** [comment]
how they heck do you fix this?

**Comment by salty-horse** [comment]
You seem to be missing smpeg.
On Fedora, try installing the package `smpeg-devel`

**Comment by AndreasDavour** [comment]
There have not been a smpeg-devel since Fedora 19. A compile switch to build without would be useful.

A README with some build instruction with pre-req packages would not hurt.

**Comment by cspiegel** [comment]
The Linux build no longer attempts to link in libsmpeg, so whenever a new Gargoyle release comes out, this won't be an issue.

Agreed on a README, and that's issue #219.  I'll try to find some time to put something together on that.
