### ISSUE TITLE
Support newlines in text input

### ISSUE THREAD

**Issue by dbedrenko** [garglk/garglk#226]
A very useful feature that is missing is to be able to paste a newline-separated list of commands to the interpreter, e.g. on timer-based games when I run out of time I want to get to the same point in the game again by pasting a walkthrough--that is, a list of commands.

Unfortunately gargoyle strips newline characters so this is currently impossible.

PS: Huge thanks for gargoyle; I love it :)

**Comment by cspiegel** [comment]
I got this working, at least, I hope I did!  If anybody wants to give it a try, there are test builds here:

[Linux AppImage](https://github.com/cspiegel/garglk/actions/runs/7895010853)
[Windows](https://github.com/cspiegel/garglk/actions/runs/7895010852)
[Mac](https://github.com/cspiegel/garglk/actions/runs/7895010856)

**Comment by cspiegel** [comment]
I've merged in #811 which implements this.
