### ISSUE TITLE
How to Install/Use Gargoyle?

### ISSUE THREAD

**Issue by Topcliffe** [garglk/garglk#229]
I'm sorry for such a basic question, but I have no background in programming or anything technical involving web apps. I simply want to use Gargoyle to play a z5 file. I've downloaded the zip, but where do I go from there? I don't see any instructions for installing and using. Thanks for your help.

**Comment by curiousdannii** [comment]
Which zip? The source code? Installers for most platforms are available at https://code.google.com/archive/p/garglk/downloads

**Comment by Topcliffe** [comment]
That's exactly what I was looking for, thanks so much for your help!

**Comment by salty-horse** [comment]
The new official location for the installers is here: https://github.com/garglk/garglk/releases
