### ISSUE TITLE
The bundled fonts have limited Unicode support

### ISSUE THREAD

**Issue by cspiegel** [garglk/garglk#230]
If font bundling is enabled, Charter BT and Luxi Mono are built into libgarglk.  However, these fonts contain poor Unicode support (see, for example, the [Spider and Web Russian translation](http://ifdb.tads.org/viewgame?id=2xyccw3pe0uovfad)).

As long as bundled fonts are supported, the included fonts ought to have a wide range of Unicode characters available.

One important consideration is that the fonts' licenses must allow for them to be incorporated directly into libgarglk, as that is how bundled fonts are implemented.

**Comment by cspiegel** [comment]
As a quick note, the popular SIL Open Font License appears incompatible with Gargoyle's font bundling, meaning many fonts are ineligible.  The relevant extract:

> 5) The Font Software, modified or unmodified, in part or in whole,
must be distributed entirely under this license, and must not be
distributed under any other license. The requirement for fonts to
remain under this license does not apply to any document created
using the Font Software.

Including the fonts in the binary would require them to be GPL, which the license forbids.

Some possible fonts:
[Linux Libertine](http://www.linuxlibertine.org/) (GPL, but no CJK)
[DejaVu](http://dejavu-fonts.org/wiki/Main_Page) (Custom, GPL-compatible, but no CJK)

[Google's Noto fonts](https://www.google.com/get/noto/), until recently, were Apache licensed, so it would also be possible to use them, but upgrades would not be possible.

**Comment by curiousdannii** [comment]
I'm not sure how garglk uses OFL fonts, but it might be okay?

> [Question: 1.11 What do you mean by 'embedding'? How does that differ from other means of distribution?](http://scripts.sil.org/cms/scripts/page.php?item_id=OFL-FAQ_web#e6faa5ad)

>Answer: By 'embedding' we mean inclusion of the font in a document or file in a way that makes extraction (and redistribution) difficult or clearly discouraged. In many cases the names of embedded fonts might also not be obvious to those reading the document, the font data format might be altered, and only a subset of the font - only the glyphs required for the text - might be included. Any other means of delivering a font to another person is considered 'distribution', and needs to be accompanied by any copyright notices and licensing information available in OFL.txt.

Distributing the source would count as an aggregate, so the GPL incompatibility wouldn't matter. If the fonts are embedded into binaries then that's not distribution according to the OFL FAQ, so section 5 of the OFL license doesn't apply.

But it would probably be better to find unambiguously safe fonts.

**Comment by BroadcastGames** [comment]
how hard is it to dynamically load the fonts for these defaults (for the sake of license issues)?

**Comment by cspiegel** [comment]
> If the fonts are embedded into binaries then that's not distribution according to the OFL FAQ, so section 5 of the OFL license doesn't apply.

I agree with this.  I missed the embedding clause earlier while I was looking through this.

> how hard is it to dynamically load the fonts for these defaults (for the sake of license issues)?

The difficulty would lie in ensuring that the fonts are where you expect them to be.  That's not actually too onerous, given that Gargoyle already needs to be able to find interpreters, so it's a solved problem.  But it's a bit easier to just keep embedding, so long as we have proper fonts, which I believe we do.

I think font handling probably should be looked at later to see if we can do it better than we currently do, but for the time being I want to keep things the same.  At least until after release.

That said, I have opened pull request #328 to switch fonts.  It includes a test build for Windows.

**Comment by cspiegel** [comment]
Fixed by #328.
