### ISSUE TITLE
Transcript is broken for non-English characters

### ISSUE THREAD

**Issue by fireton** [garglk/garglk#231]
I've downloaded and installed new version over my 2010.1 and found that trascript of my Cyrillic-based game written with all question marks. Please fix it since in 2010.1 version everything was OK.

My game can be found at [http://if.zhuchkovs.com/misc/test.z5](http://if.zhuchkovs.com/misc/test.z5) (can't attach it here)

Command for turning the transcript on is СКРИПТ ВКЛ

**Comment by cspiegel** [comment]
I just merged in the latest Bocfel release, which should fix this issue.  All transcripts are now written in UTF-8.

**Comment by fireton** [comment]
Any idea when new release is planned?

**Comment by cspiegel** [comment]
No firm date, but there's been a push on the mailing list to get a new release, so we're lumbering toward it.  The biggest blocker right now is a TADS upgrade, which I think is nearly ready.

To be qualitative, I'd say a new release will be out pretty soon.
