### ISSUE TITLE
TADS build failure with gcc 6

### ISSUE THREAD

**Issue by salty-horse** [garglk/garglk#236]
The TADS included in garglk fails to build with gcc 6, which is the default compiler shipped with Ubuntu 16.10.

This error repeats in several places:

```
tads3/vmtobj.h: In member function ‘virtual void CVmMetaclassTads::create_for_image_load(vm_obj_id_t)’:
tads3/vmtobj.h:644:34: error: exception cleanup for this placement new selects non-placement operator delete [-fpermissive]
         new (vmg_ id) CVmObjTads();
                                  ^
```

Here are relevant bugs in Debian filed against frobtads and gargoyle.
- [Debian bug #812058 - gargoyle-free](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=812058)
- [Debian bug #836934 frobtads](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=836934)

I managed to hack a fix by changing `tads/Jamfile`:

``` diff
--- a/tads/Jamfile
+++ b/tads/Jamfile
@@ -88 +88 @@ else
-SUBDIRC++FLAGS = $(SUBDIRCCFLAGS) ;
+SUBDIRC++FLAGS = $(SUBDIRCCFLAGS) -std=c++98 ;
```

(if unspecified, the default is `-std=gnu++14`)

Note that the changed line reuses the C compiler flags for C++, making it hard to pass specific flags to the C compiler, if required in the future.

While investigating this, I realized the build system is not in a good shape.
The way Jam is currently set up makes it impossible to build the entire project with a different compiler. Any custom CC and CXX settings passed to `jam` at the root of the project are ignored once it builds the "sub-project" in `tads/` (and probably others).

**Comment by cspiegel** [comment]
I have an "update TADS" branch (https://github.com/cspiegel/garglk/tree/203-tads-upgrade) I'm on-and-off working on, which builds with GCC 6.  When (if) a new release of Gargoyle happens, I will ensure that the updated TADS interpreter has been merged in, which should solve the GCC 6 problems.

As for the build system, I've also got a branch (https://github.com/cspiegel/garglk/tree/cmake) that I'm experimentally using to switch the build system to CMake.  It works just fine on Linux right now (and likely other Unix-like systems), and I've had success cross-compiling for Windows with MinGW.  It has absolutely no OS X support at the moment, however; but if it gets completed, it will at least solve the compiler issue you ran into (e.g. you can tell CMake to use a specific compiler and it will for all parts of the build).

**Comment by cspiegel** [comment]
TADS has been merged in and builds successfully for me with gcc 6.3.0.

**Comment by ShimmerFairy** [comment]
When will there be a new release with this fix? Gentoo is about to remove Gargoyle from their repo because of this build failure in 2011.1.
