### ISSUE TITLE
Photopia z-machine version 1.3, opening quote screen truncated

### ISSUE THREAD

**Issue by BroadcastGames** [garglk/garglk#238]
http://ifdb.tads.org/viewgame?id=ju778uv5xaswnlpl

On Ubuntu 16.10, self-compiled and the gargoyle-free one seem to both truncate this opening screen message, even if window resized. Thank you.

**Comment by cspiegel** [comment]
Can you please post screenshots of a non-truncated version (e.g. from another interpreter), and the truncated version you're seeing with Gargoyle?  I'm not seeing anything obviously wrong, but I'm not entirely sure what you mean by truncated here.

**Comment by BroadcastGames** [comment]
Ok, I'll look again, You know, it might have been related to the 256 width overflow... which I didn't recognize with that game - but did with zracer.

**Comment by BroadcastGames** [comment]
Ok, this took me some time to figure out!  I have a 4K resolution screen. So while it is sitting at the "do you want instructions" prompt - if I increase the window as large as it goes (about 1/2 width of the screen is allowed) - then I answer "no" to the question - I get a black screen for the quote.  Does that make sense?

If I don't resize (make larger) the default window, it appears fine.

**Comment by cspiegel** [comment]
Perfect, thank you!  I'm now able to reproduce this and will work on getting it fixed.

**Comment by cspiegel** [comment]
I've found the issue.  It'll be fixed in the next Bocfel release which will be out before the next Gargoyle release.

**Comment by BroadcastGames** [comment]
Does Bocfel have an active Github home? All the published information I could find points to the now decommissioned code.google.com pages.  For example, Bocfel has a player cheats system and related documentation: https://code.google.com/archive/p/bocfel/wikis/Cheats.wiki - does this have a new web home somewhere? Thank you and happy new year.

**Comment by cspiegel** [comment]
It's now at http://bocfel.org/ (which is currently a redirect to its actual home on Codeplex, http://bocfel.codeplex.com/).

**Comment by cspiegel** [comment]
I just merged in the latest Bocfel release, which should fix this issue.

**Comment by BroadcastGames** [comment]
Thank you.
