### ISSUE TITLE
Window resizing behavior illustrated by counterfeit-monkey

### ISSUE THREAD

**Issue by BroadcastGames** [garglk/garglk#239]
This is an observation not really a complaint. Building the latest version from source code: https://github.com/i7/counterfeit-monkey, compiled with latest Inform 7 6m62.

I observe this behavior with GarGlk on Ubuntu 16.10. 4K display resolution, single display, landscape orientation.

1. Open the GarGlk app. The initial screen has no graphics. Now resize the window to much wider before answering the first two questions in the story.
2. After answering the first two story questions, a graphical map (internal) Glk window appears on the left.
3. Resize down to the original GarGlk app window size, the graphic stays 'stuck' in the larger size. There also seems to be a maximum width that GarGlk prevents you form making the window wider.

It behaves very different in it's inability to 'shrink' the left graphics window. If you open GarGlk and never resize it before the map graphic appears, the resizing is much more 'flexible' and behaves different.  Thank you.

**Comment by curiousdannii** [comment]
This is probably a bug in the game's (unfinished) graphics code.

**Comment by cspiegel** [comment]
This isn't reproducible with the official Counterfeit Monkey.  I'll close this issue, but if a story is available that _can_ reproduce the bug, this issue can be reopened.
