### ISSUE TITLE
Stress testing Glk timer and char input, The Wilds Of Orkney.gblorb

### ISSUE THREAD

**Issue by BroadcastGames** [garglk/garglk#240]
I'm developing an interpreter app for Android and have run into some stress testing case.  This demo code sets a timer of 1 and parses key input interactively.  If found that on GarGlk if you type very fast (mash keys) and delete what you type (may take a few attempts) Gargoyle will just exit/abend.  This is on Ubuntu 16.10 with compiled version off Github and the older gargoyle-free from Ubuntu.

[The Wilds Of Orkney_gblorb.zip](https://github.com/garglk/garglk/files/681429/The.Wilds.Of.Orkney_gblorb.zip)

For information about what this code is doing: https://threeedgedsword.wordpress.com/2011/03/13/a-proposal-for-an-intelligent-if-interface/

Attached is the the game file. Thank you.

**Comment by cspiegel** [comment]
I ran this under a debugger with a breakpoint on exit(3), which helpfully kept the window open on exit.  I saw the following:

``
Glulxe fatal error: Memory access out of range (1CDDE89C)
``

The address isn't consistent (running again I got 1B9E28DC).

This seems to be a bug in the game file, although it's of course possible the interpreter is bugged, too.  I don't know anything about the Glulx file format or its interpreters, so I'm not sure how to track down the actual source.  Unfortunately I've so far been unable to determine the exact sequence of keys which causes this problem, so reproducing is hard.

It's pretty useless, because it's tracking the interpreter and not the interpreted game file, but just for completeness I'll include the stack trace:

```
#0  0x00007f6504302a90 in __GI_exit (status=0) at exit.c:104
#1  0x00007f6507be039b in  () at /usr/lib/libgarglk.so
#6  0x00007f6505c166e2 in <emit signal ??? on instance 0x700050 [GtkWindow]> (instance=instance@entry=0x700050, signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3447
    #2  0x00007f65073956bc in _gtk_marshal_BOOLEAN__BOXED (closure=0x709950, return_value=0x7fffffffc350, n_param_values=<optimized out>, param_values=0x7fffffffc400, invocation_hint=<optimized out>, marshal_data=<optimized out>) at gtkmarshalers.c:86
    #3  0x00007f6505bfb8ad in g_closure_invoke (closure=0x709950, return_value=0x7fffffffc350, n_param_values=2, param_values=0x7fffffffc400, invocation_hint=0x7fffffffc3a0) at gclosure.c:804
    #4  0x00007f6505c0d66e in signal_emit_unlocked_R (node=<optimized out>, detail=detail@entry=0, instance=instance@entry=0x700050, emission_return=emission_return@entry=0x7fffffffc4f0, instance_and_params=instance_and_params@entry=0x7fffffffc400) at gsignal.c:3635
    #5  0x00007f6505c156d9 in g_signal_emit_valist (instance=0x700050, signal_id=<optimized out>, detail=0, var_args=var_args@entry=0x7fffffffc5a8)
    at gsignal.c:3401
#7  0x00007f65074a656c in gtk_widget_event_internal (widget=widget@entry=0x700050 [GtkWindow], event=event@entry=0x9ff010) at gtkwidget.c:5010
#8  0x00007f65074a6837 in IA__gtk_widget_event (widget=widget@entry=0x700050 [GtkWindow], event=event@entry=0x9ff010) at gtkwidget.c:4807
#9  0x00007f6507393f8f in IA__gtk_propagate_event (widget=0x700050 [GtkWindow], event=0x9ff010) at gtkmain.c:2475
#10 0x00007f650739425b in IA__gtk_main_do_event (event=0x9ff010) at gtkmain.c:1696
#11 0x00007f650683c98c in gdk_event_dispatch (source=source@entry=0x6683f0, callback=<optimized out>, user_data=<optimized out>) at gdkevents-x11.c:2425
#12 0x00007f6505924027 in g_main_dispatch (context=0x6684e0) at gmain.c:3234
#13 0x00007f6505924027 in g_main_context_dispatch (context=context@entry=0x6684e0) at gmain.c:3899
#14 0x00007f6505924238 in g_main_context_iterate (context=context@entry=0x6684e0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at gmain.c:3972
#15 0x00007f65059242bc in g_main_context_iteration (context=0x6684e0, context@entry=0x0, may_block=may_block@entry=1) at gmain.c:4033
#16 0x00007f6507393511 in IA__gtk_main_iteration () at gtkmain.c:1356
#17 0x00007f6507be10f5 in gli_select () at /usr/lib/libgarglk.so
#18 0x00007f6507bc6dc0 in glk_exit () at /usr/lib/libgarglk.so
#19 0x0000000000401dbe in fatal_error_handler (str=0x41279f "Memory access out of range", arg=0x0, useval=1, val=484305052) at terps/glulxe/main.c:143
#20 0x0000000000402ae1 in verify_address (addr=484305052, count=4) at terps/glulxe/vm.c:331
#21 0x0000000000403791 in execute_loop () at terps/glulxe/exec.c:398
#22 0x0000000000401bfc in glk_main () at terps/glulxe/main.c:68
#23 0x000000000041226f in main (argc=2, argv=0x7fffffffcb08) at garglk/main.c:44
```

**Comment by cspiegel** [comment]
I just tried this again, and was able to reproduce, but I could also reproduce this with glkterm and glulxe straight from Zarf, so it's very likely a game issue.  The crash seems to happen when you hit backspace and the cursor is at the start of the line, so it may be related to bookkeeping regarding cursor position and the game just getting off a bit.

It's also possible that it's an interpreter issue: I can reproduce with Git, but that shares a lot of code with Glulxe, so if there's a bug in one, there may be a bug in another.

In either case, it doesn't appear to be a Gargoyle issue.
