### ISSUE TITLE
Cannot load game files with non-ASCII characters in the filename

### ISSUE THREAD

**Issue by erkyrath** [garglk/garglk#246]
I see this on MacOS (current and old). Trying to load a game file named "sample-ñ.t3" or "sample-∏.t3" produces an error dialog:

    Fatal error
    Unknown file type: ""
    Sorry.

**Comment by erkyrath** [comment]
Anywhere in the pathname, in fact. (User was trying to load a file in a directory, like "Français/game.z5".)

**Comment by kerrymg** [comment]
I submitted PR #250 that fixes this problem by using UTF8 encoded strings instead of ASCII.

**Comment by cspiegel** [comment]
I merged #250, so I'm closing this; please reopen if the problem persists in master.
