### ISSUE TITLE
Hugo FileIO() broken

### ISSUE THREAD

**Issue by curiousdannii** [garglk/garglk#248]
This commit applied a fix in FileIO() to the wrong line of code: https://github.com/garglk/garglk/commit/8e718a2986dfac812a940e5517d5502937a7d3b2#diff-d4a2d337b931678f8a5695dc3441df1bL942
It changed a filemode_Write to filemode_Read and left the later filemode_Read without the safety of a glk_fileref_does_file_exist() call.

I've fixed it in [my Hugo repo](https://github.com/curiousdannii/hugo) which also includes updates from [the hugo-unix repo](https://bitbucket.org/0branch/hugo-unix).

How would you like to procede? Should I submit a pull request? Do you want to switch to submodules?

Also Hugo is now BSD-2 licensed, as seen here: http://develop.generalcoffee.com/hugo/trac/browser/trunk/License.txt

**Comment by cspiegel** [comment]
For the time being I think a pull request is best.  Given that we're hopefully close to a release, I'd rather not rock the boat till after that, when we can look at better options for keeping things up to date.
