### ISSUE TITLE
MacOS lacks text-to-speech support

### ISSUE THREAD

**Issue by cspiegel** [garglk/garglk#263]
Gargoyle supports text to speech (TTS), but only on Windows and Linux (and nominally other Unix-like operating systems).  Currently it does not support OS X.

It looks like OS X has a [speech synthesis framework](https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/SpeechSynthesisProgrammingGuide/SpeechOverview/SpeechOverview.html), so presumably it should be possible to add support.  I don't have access to any OS X systems, however, so I'm unable to implement it.  I can aid in the implementation if anybody wants to take it on, although Gargoye's TTS system is very straightforward as it stands.

Because OS X is Unix-like it may be possible to use the existing Linux/Unix backend (based on [speech-dispatcher](https://devel.freebsoft.org/speechd)), but I'd assume that the native speech synthesis API is preferable.

**Comment by kerrymg** [comment]
I have submitted PR #266 that adds preliminary TTS support to macOS builds.

Feedback, criticisims, and enhancement suggestions are more than welcome.

**Comment by cspiegel** [comment]
OS X support now exists thanks to @kerrymg.  Closing as done.
