### ISSUE TITLE
Travis does not test OS X

### ISSUE THREAD

**Issue by cspiegel** [garglk/garglk#279]
There is no Travis build test for OS X.

**Comment by curiousdannii** [comment]
What would the command to build it on OS X be?

I can try to figure out the Travis matrix, but I don't know what to run on OS X.

**Comment by cspiegel** [comment]
I've never built anything on OS X, but Andrew Plotkin added the following to the INSTALL file earlier this year, so it should be up to date:

The new build script (contributed by Brad Town) can be run on any
MacOS 10.7 or higher. It requires a set of Unix packages (see below),
which can be installed with either MacPorts or Homebrew. If you're
building Gargoyle for your own use, that's all you need to know.

For the MacPorts packages you'll need, type:

  sudo port install libsdl -x11
  sudo port install libsdl_mixer libsdl_sound
  sudo port install libpng
  sudo port install jpeg
  sudo port install smpeg
  sudo port install freetype
  sudo port install pkgconfig
  sudo port install jam

If you're using Homebrew, instead type:

  brew install sdl
  brew install sdl_mixer sdl_sound
  brew install libpng
  brew install jpeg
  brew install smpeg
  brew install libvorbis
  brew install freetype
  brew install pkg-config
  brew install jam

Once the packages are installed, type:

  sh gargoyle_osx.sh

This should create Gargoyle.app, and also build a .DMG file which
contains the app.
