### ISSUE TITLE
AdvSys - which story data files should run? "bad data file"

### ISSUE THREAD

**Issue by WakeRealityDev** [garglk/garglk#282]
I tried http://ifdb.tads.org/viewgame?id=mt1zi26l1zejnsxy - is this story supposed to be compatible with AdvSys interpreter?  If not, can someone point me to a data file that should work?  Thank you.

**Comment by salty-horse** [comment]
Works for me. Which version of Gargoyle are you using, and what is the exact error you're getting?

**Comment by WakeRealityDev** [comment]
Ok, I must be chasing my tail.  Error was "bad data file" no matter what I tried. I did a reboot of my Ubuntu system and a fresh build and it works now. I'll close.
