### ISSUE TITLE
garglk.ini does not support Unicode

### ISSUE THREAD

**Issue by alysdexia** [garglk/garglk#287]
nor does it seem to support any Windows or DOS encoding fully; it looks like it natively encodes ISO-8859-1 Latin-1 Western Europe which includes most of the Windows 1252 Western European set but not several figures after the tilde like Euro, horizontal ellipsis, dash. I would like to use the ellipsis as the moreprompt but find I can't.
https://bocfel.codeplex.com/workitem/1

**Comment by cspiegel** [comment]
I can successfully use a Unicode ellipsis as the more prompt both on Unix and Windows, with it being UTF-8 in both cases.  This bug report was added when the 2011 release was current, so this is probably no longer valid.

UTF-8 is the only supported encoding now, for anything, so if this still doesn't work with the latest release, with a UTF-8 garglk.ini, please let me know.

**Comment by KarolS** [comment]
Does "the latest release" mean 2019.1.1? If so, then I can reproduce the problem on Windows 10:

    moreprompt  …

gives 

![obraz](https://user-images.githubusercontent.com/1790750/140795224-eff8374f-5ea6-4650-83f3-7ad039204706.png)

**Comment by cspiegel** [comment]
Great question, because I didn't even think to check 2019.1.  I can reproduce the problem in 2019.1, but not the latest master (to be 2021.1), so while this is still a bug in the wild, it's fixed, and will be out shortly in a release.

Thanks for re-testing.  If you're interested I can create a Windows installer from the latest master, so you can see if it is fixed for you there; it does work for me, but I never mind being double-checked (again!)

**Comment by KarolS** [comment]
I guess if it's fixed in master and is only awaiting the release, then it should be okay. The 2019.1 version is 2 years old after all, it's normal that it contains old bugs.

Although I wouldn't mind testing a build if there's a chance that #341 has been fixed.

**Comment by cspiegel** [comment]
I've now got the automated MinGW build producing installers, so going forward, all branches/commits will produce installers.  Current master is now available here:

https://github.com/garglk/garglk/actions/runs/1440005049

You can download the "Gargoyle" artifact, which contains both 32- and 64-bit installers.

**Comment by KarolS** [comment]
![obraz](https://user-images.githubusercontent.com/1790750/141216419-2e03684f-a626-4ca9-916f-c33b23f595de.png)
Everything works fine in that build

**Comment by cspiegel** [comment]
Great, thanks for testing!
