### ISSUE TITLE
FreeType doesn't accept other local fonts in garglk.ini

### ISSUE THREAD

**Issue by alysdexia** [garglk/garglk#288]
You promise
>Fonts, sizes and spaces
>(Tweak this if you choose other fonts, or want bigger text)

but when I edit the fonts to anything other than the defaults, presumably buried in libgarglk.dll as mentioned in #230, the interpreter fails with "FT_Open_Face: [font name]: 0x1".  I tried every format of name, with and without extension and word separators.  Instead of the LuxiMonos and CharterBTs I substituted the better Input Monos and Bitstream Cyberbit Romans, Vollkorns, and Segoe UIs to no avail.

**Comment by alysdexia** [comment]
Mostly good news!  After some more googling I found that the file needed a path instead of the font name, but I don't know why the font name works for some.  However the copy of Bitstream Cyberbit has no separate files for each of the styles, so I don't know how to add the bold, italic, etc. unless the same file works for all of them.  I'm stuck with "\Windows\Fonts\Cyberbit.ttf".

**Comment by cspiegel** [comment]
I assume this is the 2011.1 release available here?

I don't really understand Windows font loading, but a cursory test with Wine on Linux allows me to just use font names, not full paths, and they will be loaded properly.  The function that's used to enumerate fonts is documented as being able to load fonts via name, not path, too.  What version of Windows are you testing this on?  If I can find a similar Windows system I can test there.

As for Bitstream Cyberbit, it's Roman only.  However, Gargoyle includes code to automatically convert fonts to bold/oblique where necssary, and when I use Bitstream Cyberbit, the conversions happen, both in Linux and Wine.  Again, once I get a Windows machine to test on I'll be able to better check things, but it's a bit surprising that at least the bold/oblique changes aren't occurring.

**Comment by cspiegel** [comment]
OK, I was able to test this on Windows 10, and couldn't reproduce the issue.  System fonts loaded fine (I tested Arial, Segoe UI, and Consolas).  I also tested Bitstream Cyberbit, and it properly synthesized bold, oblique, and bold oblique versions.

If you attach the garglk.ini you used, as well as the Windows version, I can try to look into it more, but as it stands, everything is working for me.

**Comment by alysdexia** [comment]
I found the cause.  propfont and monofont do take names but each of the styles (propr, propb, propi, propz, etc.) only take paths.

**Comment by cspiegel** [comment]
Hm, I'm not even sure why the prop* and mono* options are available.  They're not exposed in the sample garglk.ini file and I'm inclined to simply remove the ability to set them.  They're implicitly set by propfont and monofont, so unless there's a great clamoring for the ability to use different font faces for, say, Roman vs Italic, I don't see any reason to expose them.

**Comment by alysdexia** [comment]
They're exposed in the Windows build:

monor         LuxiMonoRegular
monob         LuxiMonoBold
monoi         LuxiMonoOblique
monoz         LuxiMonoBoldOblique

propr         CharterBT-Roman
propb         CharterBT-Bold
propi         CharterBT-Italic
propz         CharterBT-BoldItalic

**Comment by cspiegel** [comment]
Alright, it looks like the 2011.1 Windows release includes an older garglk.ini.  propfont/monofont replaced the “rbiz” options back in 2010.  I suppose it doesn't hurt to keep them for backwards compatibility with older garglk.ini files, but the propfont/monofont options are the way to select fonts these days.
