### ISSUE TITLE
Can you make the interpreters remember window position?

### ISSUE THREAD

**Issue by alysdexia** [garglk/garglk#289]
Or write it to garglk.ini.  It's damned annoying makan me move the window back every time I launch.

**Comment by cspiegel** [comment]
This has been supported on non-Mac platforms for a while, but I've finally gotten around to adding support for Mac, as well, in #809.  It's not perfect, as the location saved is a bit off (around 20 pixels), but it's pretty close.  I'll try to fix it up, or get Mac moved over to Qt (which should also fix it), but for now, it's not too bad.

You have to enable it in your config file:

```
# Gargoyle can try to restore the last window size and window location.
# This is generally only provided as a hint to the window system, and
# may be ignored. The value is whitespace-delimited strings taking the
# value "size" or "location":
#
# save_window size
# save_window location
# save_window size location
#
# The default is to save neither. If Gargoyle is able to restore a
# saved window size, then the "cols" and "rows" settings are ignored.

**Comment by cspiegel** [comment]
#809 has been merged in.  I'll try to improve this but for now it's a lot better than it was.
