### ISSUE TITLE
License issues

### ISSUE THREAD

**Issue by fireton** [garglk/garglk#295]
My point is this. I want to distribute my game as Windows installer package bundling interpreter **and** z5 file.  Question: is it ok use Gargoyle as bundled interpreter for running the game or it's against it's license? 

For instance, is GPL terms apply to my game source code if I bundle my game with Gargoyle? This part I didn't figure out.

**Comment by cspiegel** [comment]
Ultimately an attorney is the best source of information on licensing.  That said, the answer is certainly no, because the story file is a separate work from Gargoyle or any of its interpreters.  The GPL applies to modifications/derivatives of the work, neither of which a story file is.

**Comment by curiousdannii** [comment]
That would be considered an ["aggregate"](https://www.gnu.org/licenses/gpl-faq.en.html#MereAggregation).

@cspiegel This has made me notice that it doesn't seem to be specified anywhere (or at least not easily noticeable) which version of the GPL is used here. That's important - GPL 2 and 3 are not actually compatible. This may need to be a question for Tor, but it should be answered.

**Comment by fireton** [comment]
That's cool I guess. That would be the way to make my game more available to people who not much into computers. Simple installer and icon on  desktop. Thanks!
