### ISSUE TITLE
Gargoyle still trying to load libpng12.so

### ISSUE THREAD

**Issue by curiousdannii** [garglk/garglk#309]
> ./build/dist/gargoyle: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory

When I try to build the current master it seems to be trying to load 1.2 instead of 1.6.

**Comment by cspiegel** [comment]
When built from source, Gargoyle doesn't care about which version of libpng you have.  It looks up where to find libpng via `pkg-config`, and will use whatever library it finds that way.

There are two things I can think of off hand:

1. It's possible that `pkg-config` is forcing a link against an installed libpng 1.2 that's not available to the dynamic linker.  Can you post the output of `pkg-config libpng --libs`?  That should indicate which libpng Gargoyle will link to.

2. It's also possible that Gargoyle is linking to the proper libpng, but that another library along the line references the older libpng.  I'd expect a link failure in this case, but you never know...  Can you post the output of both the following?

`ldd build/dist/gargoyle`
`objdump -x build/dist/gargoyle | grep NEEDED`

In the meantime, I'll try to find time to set up Ubunutu in a VM and reproduce this.

**Comment by curiousdannii** [comment]
```
dannii@ub1510:~/garglk$ pkg-config libpng --libs
-lpng16 -lz
dannii@ub1510:~/garglk$ ldd build/dist/gargoyle
...
	libpng12.so.0 => not found
...
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007fa0538c3000)
...
dannii@ub1510:~/garglk$ objdump -x build/dist/gargoyle | grep NEEDED
  NEEDED               libgarglk.so
  NEEDED               libm.so.6
  NEEDED               libgtk-x11-2.0.so.0
  NEEDED               libgdk-x11-2.0.so.0
  NEEDED               libgobject-2.0.so.0
  NEEDED               libc.so.6
```

**Comment by kerrymg** [comment]
FWIW, I just built Gargoyle from a fresh checkout of the master branch on a newly installed Ubuntu 17.04 VM. It builds and runs correctly, no dependance on `libpng12`.

Try `objdump -x build/dist/libgarglk.so | grep NEEDED` to see which PNG library Gargoyle's Glk library depends on directly. It should only be `libpng16` which is what I'm seeing:
```
  NEEDED               libgtk-x11-2.0.so.0
  NEEDED               libgdk-x11-2.0.so.0
  NEEDED               libgobject-2.0.so.0
  NEEDED               libglib-2.0.so.0
  NEEDED               libfontconfig.so.1
  NEEDED               libfreetype.so.6
  NEEDED               libpng16.so.16
  NEEDED               libSDL_mixer-1.2.so.0
  NEEDED               libSDL-1.2.so.0
  NEEDED               libjpeg.so.9
  NEEDED               libSDL_sound-1.0.so.1
  NEEDED               libc.so.6
```
 If that's the case, then some other library is probably loading it. It might be possible to figure it out from the output of `ldd` using the `-v` option (`ldd -v build/dist/gargoyle`).

**Comment by curiousdannii** [comment]
Right so that last command shows this:

```
	/usr/lib/libgarglk.so:
		libpng12.so.0 (PNG12_0) => not found
```

I guess it's trying to use some old version of Gargoyle.

So I deleted /usr/lib/libgarglk.so, rebuilt Gargoyle from scratch, and now it's say

```
./build/dist/gargoyle: error while loading shared libraries: libgarglk.so: cannot open shared object file: No such file or directory
```
Even though libgarglk.so is in the dist folder right next to gargoyle!

**Comment by cspiegel** [comment]
Somehow I keep forgetting that Gargoyle builds libgarglk as a shared library...

On Linux, shared libraries are not searched for in the same directory as the binary that relies on them.  Instead, a standard set of paths is consulted.  However, this can be augmented with the environment variable `LD_LIBRARY_PATH`, which points to a directory containing shared libraries to search.  You can do this with:

```
LD_LIBRARY_PATH=$PWD/build/dist ./build/dist/gargoyle
```
That should cause Gargoyle to search first in the `dist` directory for `libgarglk.so`.

**Comment by kerrymg** [comment]
I ran into the same `error while loading shared libraries` problem that @curiousdannii had. I had to do a "system" install (plus the steps listed in the `INSTALL` file) to get my newly built Gargoyle to run.

Apparently you can load shared libraries in the same directory as the executable by setting the proper `rpath` at the link stage. I'll take a look at adding `rpath` option(s) to the linker command line. It will be very handy to run test versions of Gargoyle without having to install them.

**Comment by kerrymg** [comment]
The following one-line addition to the `Jamrules` file modifies the link phase to add an `RPATH` entry pointing to the executables own directory as a place to search for shared libraries. With this change one can launch the various Gargoyle executables directly from the `./build/dist/` directory.

```diff
diff --git a/Jamrules b/Jamrules
index b0abdd0..7200676 100644
--- a/Jamrules
+++ b/Jamrules
@@ -126,6 +126,7 @@ switch $(PLATFORM)

        # Not all supported platforms include a png-config file for libjpeg.
        GARGLKLIBS = "`$(PKGCONFIG) --libs`" -ljpeg ;
+       LDFLAGS = "-Wl,-rpath='$ORIGIN'" ;
        LINKLIBS = -lm "`$(PKGCONFIG) --libs`" ;

        # SDL_sound does not include a png-config file.
```

The patch works on Linux (Ubuntu 17.04 for sure, probably other Linux OS' too). I'm not sure what effect this change would have on BSD-based systems and other Unixes Gargoyle supports.

**Comment by curiousdannii** [comment]
Thank you, that seems to be working perfectly now.

**Comment by cspiegel** [comment]
Jam is no longer used, and CMake knows how to set the rpath, so this should be resolved.
