### ISSUE TITLE
Mouse Input Events broken by retina/zoom change?

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#315]
I haven't tested this properly, but it seems that at least clicking on the compass rose in Counterfeit Monkey no longer works after b4a966f on my retina Mac.

**Comment by hkleinsorgen** [comment]
Observed on Linux and Windows, too. I've fixed this issue, see [pull request  318](https://github.com/garglk/garglk/pull/318)

**Comment by angstsmurf** [comment]
Thanks a lot for fixing this!
