### ISSUE TITLE
Zoom wrong during live resizing on macOS

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#320]
When resizing the window manually, the contents will momentarily be twice the normal size.

See https://youtu.be/z6v8k6xpDr8

**Comment by cspiegel** [comment]
@townba @hkleinsorgen The HiDPI changes appear to have some unintended consequences. I'm wary of preparing a release soon which will incorporate them without sufficient testing time.  I'm pondering reverting the changes in preparation for a release, and then we can try to get them right.  Please let me know your thoughts on this.

I don't have a HiDPI display, nor access to an OS X system.  I can't run Gargoyle on anything beyond Linux/BSD natively, and Windows via Wine, which makes it difficult for me to fully test everything.

**Comment by angstsmurf** [comment]
In my opinion, this is a minor cosmetic issue that is acceptable in a release version. Resizing the window is not something you do often, and it has always had issues in this and other interactive fiction interpreters, such as the status bar no longer filling the width of the window.

Even with this glitch, Gargoyle is a now a lot more pleasant to use on a HiDPI screen than before the changes. Unless other problems are found, I'd say go ahead and include it in a release.

**Comment by cspiegel** [comment]
@angstsmurf I'm not concerned so much with this particular issue; rather, it's any other potential unknowns that arise, given that there have been a couple issues already.  However, if you have/are willing to do some OS X testing across a few varied games, I'm OK doing the release, given how much better you say it looks.  Thanks for the testing and reports so far.  It's really helpful to have testing done, especially on configurations I don't have access to.

**Comment by angstsmurf** [comment]
That is true, but I think the sudden change in text size, as illustrated by the video, makes it look worse.

**Comment by angstsmurf** [comment]
I have been running Gargoyle with #322 applied on my Retina MacBook Pro for a while now, and this issue is fixed.
