### ISSUE TITLE
Text double size on standard DPI screen

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#321]
With the new HiDPI changes, text will be will be double size on a standard DPI screen. When dragging from a standard DPI screen to a HiDPI or the other way, the text will change size. Only tested on macOS.

**Comment by hkleinsorgen** [comment]
I have a patch for this issue and #320, which are closely related. Needs some cleanup, though.
On Windows I haven't observed such issues so far (except for the problem with the status bar).

**Comment by angstsmurf** [comment]
That is great! Please consider making a pull request with the WIP code, so that it doesn't get lost.

**Comment by angstsmurf** [comment]
As per my comment on #320, this is fixed by  #322.
