### ISSUE TITLE
Please remove non-free fonts

### ISSUE THREAD

**Issue by donaldr3** [garglk/garglk#327]
Fonts under this Luxi license are unfortunately non-free. Could you please replace them with free fonts? You can learn about free licenses for fonts here <https://www.gnu.org/licenses/license-list.en.html#Fonts>, and also can find free fonts via the Free Software Directory <https://directory.fsf.org>. Thank you.

**Comment by cspiegel** [comment]
Is this an issue of a license violation, or is it a philosophical argument against a particular license?

**Comment by nickbe** [comment]
I quote from the license:

> Luxi fonts copyright (c) 2001 by Bigelow & Holmes Inc. Luxi font instruction code copyright (c) 2001 by URW++ GmbH. All Rights Reserved. Luxi is a registered trademark of Bigelow & Holmes Inc.
> 
> Permission is hereby granted, free of charge, to any person obtaining a copy of these Fonts and associated documentation files (the “Font Software”), to deal in the Font Software, including without limitation the rights to use, copy, merge, publish, distribute, sublicense, and/or sell copies of the Font Software, and to permit persons to whom the Font Software is furnished to do so, subject to the following conditions:
> 
> The above copyright and trademark notices and this permission notice shall be included in all copies of one or more of the Font Software.

So, all they want is to include the copyright notice in the distributed files. No problem then as far as I can see.

**Comment by donaldr3** [comment]
> The Font Software may not be modified, altered, or added to, and
in particular the designs of glyphs or characters in the Fonts may
not be modified nor may additional glyphs or characters be added
to the Fonts. This License becomes null and void when the Fonts or
Font Software have been modified.

Is the problematic text in the license.

**Comment by curiousdannii** [comment]
The fonts are known to be non-free, as are some of the interpreters. Some Linux OSes distribute gargoyle-free which excludes these.

It could be worth considering publishing a -free version here in the next release, it's probably not much work compared to everything that's been done to get to the stage of doing a new release.

**Comment by cspiegel** [comment]
A few points:

- On the whole, I'm in favor of a freer license.
  - In this case it's not like the BSD vs. GPL issue, where the definition of "free" matters: in this case there are licenses I'd say are, essentially, strictly better than the Luxi license.  If a license says you are free to distribute (like Luxi) *but* can also modify it, then it's better than the Luxi license.
- I don't think the issue of the Luxi license is a show-stopper in and of itself.  That is, even though I'd prefer a freer license, I don't personally care that Luxi doesn't fit some group's definition of "free".
- We already have issue #230 of which this issue is, basically, a duplicate, so the replacement of Luxi Mono is already on the radar.
- But....

Gargoyle bundles fonts by default and bundled fonts are handled by directly including the font into the libgarglk binary.  Given that libgarglk is GPL, I think that bundled fonts must be compatible with the GPL, and because you can't modify Luxi, I don't think it is compatible.

With that in mind, it seems necessary to me to implement #230 before release.  I did some experimenting with this long ago during the #230 discussion: https://github.com/cspiegel/garglk/tree/230-unicode-fonts

I've chosen [Noto Serif](https://www.google.com/get/noto/#serif-lgc) and [Go Mono](https://blog.golang.org/go-fonts) for their similarity to Charter BT and Luxi Mono.  I'd prefer to avoid bikeshedding on the font issue, but if there are any material objections to these fonts, by all means, raise them.

**Comment by cspiegel** [comment]
I've created pull request #328 to address #230 (which will also address this ticket).

**Comment by cspiegel** [comment]
Fixed by #328.

**Comment by Tynach** [comment]
@cspiegel @nickbe, I do have a comment about this, especially when using gamma correction. Noto Serif is not terrible, but not nearly as crisp as Bitstream Charter. Additionally, Bitstream Charter was actually forked and extended with better Unicode support under the name [Charis SIL].

As for the Luxi fonts' license, I find it kinda funny that you narrowed in on Go Mono. I can't find it mentioned anywhere in any documentation for that font, but if you just compare Go Mono and Luxi Mono, it becomes very clear very quickly that Go Mono is *definitely* a derivative of Luxi Mono.

Maybe they re-created the curves from scratch, but I can swap back and forth between the two in KDE's font manager and watch most of the letters just barely change shapes, while everything stays precisely the same size. And the bottom of lowercase 'e' has one of its points moved up slightly while the rest stay identical.

It's the perfect replacement for Luxi Mono, and I can't find anyone anywhere else on the Internet pointing out the similarities. Good job finding it!

[Charis SIL]: https://software.sil.org/charis/

**Comment by nickbe** [comment]
@Tynach I just tested Charis SIL and it's indeed excellent and I would like to see it as the default replacement for noto.
@cspiegel Do you think we could integrate it into Gargoyle and release it 😄 ?

**Comment by cspiegel** [comment]
The problem with Charis SIL is that it's licensed under the [SIL Open Font License](https://scripts.sil.org/cms/scripts/page.php?item_id=OFL_web), which contains, in part:

> The OFL allows the licensed fonts to be used, studied, modified and
redistributed freely as long as they are not sold by themselves. The
fonts, including any derivative works, can be bundled, embedded,
redistributed and/or sold with any software provided that any reserved
names are not used by derivative works. The fonts and derivatives,
however, cannot be released under any other type of license. The
requirement for fonts to remain under this license does not apply
to any document created using the fonts or their derivatives.

...

> 5) The Font Software, modified or unmodified, in part or in whole,
must be distributed entirely under this license, and must not be
distributed under any other license. The requirement for fonts to
remain under this license does not apply to any document created
using the Font Software.

When fonts are bundled in Gargoyle, they are directly included in the `libgarglk.so` file. This is covered by Gargoyle's license, which is GPL.

I originally would have used Charis SIL but for this restriction...

It's fine to include the Charis SIL font files separately from the binary, so this could be a path toward using Charis SIL.  The macOS build already operates like this: bundled fonts aren't used, but instead it includes the font files in the DMG file.  It shouldn't be too difficult to do the same thing for Windows and Unix.  That would mean that if the font files, for some reason, don't exist, Gargoyle won't have anything to fall back onto, but that's not onerous: if the interpreters aren't in the right place, Gargoyle isn't useful either, so it's not as though this is unprecedented.

**Comment by cspiegel** [comment]
I think bundled fonts probably _do_ still need to be included, just so there _is_ a fallback (no harm there), but that can be a last resort.

The "problem", so to speak, is that Gargoyle looks up fonts (specified with `propfont` and `monofont`) in the system font database, e.g. FontConfig on Unix.  So it can't just specify `propfont Charis SIL` in the default ini file, since, even if it includes the font files, they wouldn't become system font files (and Gargoyle has no business installing fonts globally, _unless_ they have been modified to indicate they're from Gargoyle).

As an initial thought, fonts would have to look something like this:

* Is `propfont` provided?
  * Yes: Look font files up based on it (go to "No" below on failure?)
  * No: Do the Charis SIL files (Regular, Bold, Italic, Bold Italic) exist where they're expected to?
     * Yes: Load them
     * No: Use the bundled Noto Serif

It's a bunch of contortions to work around licensing issues, especially when users are able to specify their own fonts in the config file, but maybe it's worth it.

**Comment by Tynach** [comment]
@cspiegel, I see. I had another idea for a solution, but it actually brings up a different issue entirely.

The version of Gargoyle available in Debian's repositories puts all the interpreter binaries in a separate directory under `/usr/lib`, and I figured you could just put the font files in there. But when I compile the code with `jam install`, it dumps all binaries into `./build/dist`; and if I 'install' all of those by copying them into a directory in my `PATH`, the one named `git` overrides my system's copy of `git`.

I don't actually understand how to control this. I have an install prefix in my home folder that I use with other software I compile, which I have added to my user's PATH environment variable, but I don't know enough about Jam to figure out how to get it to use that (other than the fact that setting the `LD_RUN_PATH` env. variable also affects the RPATH/RUNPATH attribute of the built executable files, so at least I can configure where to put `libgarglk.so`; I figured that out by accident though).

I imagine there might be similar problems for the font files; different distros might package them to be placed in different places on the system, and you'd need a way for them to specify where that is. Maybe a preprocessor definition that's set by the build tools?

**Comment by cspiegel** [comment]
> The version of Gargoyle available in Debian's repositories puts all the interpreter binaries in a separate directory under `/usr/lib`, and I figured you could just put the font files in there. But when I compile the code with `jam install`, it dumps all binaries into `./build/dist`; and if I 'install' all of those by copying them into a directory in my `PATH`, the one named `git` overrides my system's copy of `git`.

Normally Gargoyle will look in the same directory as the `gargoyle` binary for all the interpreters.  So whatever directory `gargoyle` is in, that's where the interpreters should be.  Debian changes that up, though: they hardcode `/usr/lib/gargoyle` as the location of the interpreters (by patching `launchgtk.c`).

> I imagine there might be similar problems for the font files; different distros might package them to be placed in different places on the system, and you'd need a way for them to specify where that is. Maybe a preprocessor definition that's set by the build tools?

Yeah, the way Gargoyle does it now isn't exactly ideal.  I don't really want to touch the Jam build system much, but your suggestion is something I've been hoping to be able to do with CMake: have specific directories for Gargoyle data, so we'd have (for example) `/usr/libexec/gargoyle/<interpreters>` and `/usr/share/gargoyle/<fonts>`, or whatever.  The framework for this in CMake is trivial with CMake's GNUInstallDirs, but of course the code would need to be updated to handle it, although that's not a huge task.

The caveat is that Windows and macOS need to continue to work, and the GNUInstallDirs part is really only relevant for non-Mac Unix systems.

**Comment by nickbe** [comment]
It would surely be simply possible to simply contact the creators of Charis SIL and ask them for a definete permission for gargoyle. A colleague of mine had contact regarding another open source software project and told me that they were very friendly and forthcoming.

**Comment by ann-bush** [comment]
You can redistribute the Charis SIL or any other font with an open font open font license by including the relevant copyright documents.   I don't understand why you can't do that.  Is the font embedded into Gargoyle?  If that's the case, there are allowances for that too.

**Comment by cspiegel** [comment]
> It would surely be possible to simply contact the creators of Charis SIL and ask them for a definete permission for gargoyle. A colleague of mine had contact regarding another open source software project and told me that they were very friendly and forthcoming.

I think the real problem with that would be that even if Gargoyle were granted the right to do whatever we want with the font for this project only, the viral nature of the GPL would force the font to be distributed under the GPL.  That would likely make any exemptions a non-starter, since the font itself would then effectively be GPL, which I assume is _not_ the desire of SIL.

**Comment by cspiegel** [comment]
> You can redistribute the Charis SIL or any other font with an open font open font license by including the relevant copyright documents. I don't understand why you can't do that. Is the font embedded into Gargoyle? If that's the case, there are allowances for that too.

Yes, it is embedded.  Gargoyle is GPL, which is not compatible with the SIL Open Font License, so although the OFL allows for embedding, the license terms clash with those of the GPL.

I may just go the route of creating renamed versions of the fonts such as "Gargoyle Mono" and "Gargoyle Serif" (both the Go and Charis SIL font licenses allow this), and require them to be installed system-wide, removing bundling entirely.  Linux distributors would have to do the right thing, but nobody should have a problem installing fonts that won't clash with any other fonts.

**Comment by ann-bush** [comment]
According to the FAQ document, if it's embedded, you do not need to include the license (if you can't)  It says Answer: The only situation in which an OFL font can be distributed without the text of the OFL (either in a separate file or in font metadata), is when a font is embedded in a document or bundled within a program. In the case of metadata included within a font, it is legally sufficient to include only a link to the text of the OFL on https://scripts.sil.org/OFL, but we strongly recommend against this. Most modern font formats include metadata fields that will accept the full OFL text, and full inclusion increases the likelihood that users will understand and properly apply the license.

**Comment by cspiegel** [comment]
> According to the FAQ document, if it's embedded, you do not need to include the license (if you can't) It says Answer: The only situation in which an OFL font can be distributed without the text of the OFL (either in a separate file or in font metadata), is when a font is embedded in a document or bundled within a program. In the case of metadata included within a font, it is legally sufficient to include only a link to the text of the OFL on https://scripts.sil.org/OFL, but we strongly recommend against this. Most modern font formats include metadata fields that will accept the full OFL text, and full inclusion increases the likelihood that users will understand and properly apply the license.

That FAQ answer is only about whether the text of the license itself needs to be included. The font is still covered under the OFL, even if it doesn't come with the text of the OFL. As a result, it's still incompatible with the GPL.

If it's determined that it's worth including Charis as a default, we'll use a workaround that doesn't involve embedding.

**Comment by Tynach** [comment]
@ann-bush, there seems to be a misunderstanding.

> According to the FAQ document, if it's embedded, you do not need to include the license (if you can't) It says Answer: The only situation in which an OFL font can be distributed without the text of the OFL (either in a separate file or in font metadata), is when a font is embedded in a document or bundled within a program.

The way Gargoyle is currently set up, the font would be converted into a hexdump, and that hexdump is converted into a C source file that gets `#include`ed. In effect, the font is indeed embedded, but not into a document. And it's not bundled with the program, it's *embedded* in the program.

The source file in question for the current default, Noto Serif, is here:
https://raw.githubusercontent.com/garglk/garglk/master/garglk/NotoSerif-Regular.hex

The OFL allows this ('The fonts, including any derivative works, can be bundled, embedded, redistributed and/or sold with any software provided that any reserved names are not used by derivative works.'), but also requires that, if combined with another piece of software, requires the whole thing to be released under the OFL... And the GPL likewise requires the whole of a combined work to be under the GPL. This makes the two incompatible.

After Googling a bit, I found [this comment]. It contains the response from the FSF when asked to clarify this situation. This paragraph is the most relevant bit:

> It is of course possible that you could create a combined work depending on how implementation is done. Such cases should be avoided with works licensed under the GNU GPL, because the SIL OFL 1.1 is incompatible with the GNU GPL. This is because Section 5 of SIL OFL 1.1 has the following requirement that is incompatible with the terms of the GNU GPL: "The Font Software, modified or unmodified, in part or in whole, must be distributed entirely under this license, and must not be distributed under any other license." This is incompatible with the terms of the GNU GPL, because the GNU GPL has a similar statement that requires the entire work to be under the terms of the GNU GPL.

Currently, this is how Gargoyle bundles fonts - by creating this kind of combined work.

[this comment]: https://github.com/FortAwesome/Font-Awesome/issues/1124#issuecomment-29507471

**Comment by jvgaultney** [comment]
@Tynach That is correct. You can't combine an OFL font with GPL software in this way. We'd also not be willing to release a GPL version of Charis SIL. The inability to combine OFL fonts is going to be an ongoing problem for your project, in that the OFL has become the de facto standard for the great majority of free/libre fonts. It would be worth your effort to find a way to bundle the fonts rather than combine them. 
[ Senior Type Designer, SIL, and co-author of the SIL Open Font License ]

**Comment by nickbe** [comment]
Thanks for joining here Victor 😀
