### ISSUE TITLE
Unicode line input in status window crashes test

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#330]
https://eblong.com/zarf/glulx/inputeventtest.ulx

`>PUSH STATUS. GET UNICODE LINE
`

Game closes with error:
Glk library error: put_buffer: window has pending line request
Glk library error: put_buffer: window has pending line request
Glk library error: put_buffer: window has pending line request

It seems that standard line input works on Windows but crashes on Mac, but I haven't been able to test the same version of Gargoyle on both platforms.

**Comment by kerrymg** [comment]
I found *a* bug with Unicode input in status window while trying to duplicate this problem. I have submitted PR #332 that fixes it.

Any chance that that you could test a build with the fixes in the PR to see if it resolves this issue. I have not been able to reproduce this problem exactly as described.

**Comment by angstsmurf** [comment]
You are correct that this won't happen if I make the window wider. If I change the line
`[ Git Glulxe ]          cols          80              # longer lines for Glulx games`
in preferences to
`[ Git Glulxe ]          cols          81              # longer lines for Glulx games`
it will also not happen, so I guess it wouldn't hurt to change this default.

I will try out #332 and get back to you.

**Comment by angstsmurf** [comment]
I think this can be closed now.
