### ISSUE TITLE
Typing does not work in macOS 10.13.6 (High Sierra)

### ISSUE THREAD

**Issue by juandesant** [garglk/garglk#343]
I have tried several games, and none of them work, not accepting text input.

I even tried the sample input checking game http://eblong.com/zarf/glulx/inputeventtest.ulx to no avail.

Not sure if it is the same issue as for #232, but in any case I have tried a number of releases on 10.13.6.

**Comment by juandesant** [comment]
This release from @erkyrath's fork seems to fix it.

https://github.com/erkyrath/garglk/releases/tag/zarf-mac-20180812

**Comment by cspiegel** [comment]
The latest release had enough testing with no issues that I think this issue is no longer valid.
