### ISSUE TITLE
Feature request: Night mode

### ISSUE THREAD

**Issue by ElonSatoshi** [garglk/garglk#345]
The bright whites burns my eyes!

**Comment by cspiegel** [comment]
You can set colors manually through the Gargoyle config file.  For example, the following is similar to the Slate theme from Lectrote:

```
windowcolor   4d4d4f
caretcolor    ffffff
morecolor     00cc00
tcolor  0     ffffff  4d4d4f
tcolor  1     ffffff  4d4d4f
tcolor  2     ffffff  4d4d4f
tcolor  3     ffffff  4d4d4f
tcolor  4     ffffff  4d4d4f
tcolor  5     ffffff  4d4d4f
tcolor  6     ffffff  4d4d4f
tcolor  7     ffffff  4d4d4f
tcolor  8     ffffff  4d4d4f
tcolor  9     ffffff  4d4d4f
tcolor 10     ffffff  4d4d4f
gcolor  0     333333  ffffff
gcolor  1     333333  ffffff
gcolor  2     333333  ffffff
gcolor  3     333333  ffffff
gcolor  4     333333  ffffff
gcolor  5     333333  ffffff
gcolor  6     333333  ffffff
gcolor  7     333333  ffffff
gcolor  8     333333  ffffff
gcolor  9     333333  ffffff
gcolor 10     333333  ffffff
```
As for where the config file lives, on Unix systems it's `$HOME/.garglkrc`.  On Windows systems it's actually the same (also `$HOME/garglk.ini`) although I don't know if Windows sets $HOME.  Alternatively on Windows, there is a `garglk.ini` file in the same location as `gargoyle.exe`, e.g. `C:\Program Files (x86)/Gargoyle`, which you can modify.

If the `$HOME/.garglkrc` file doesn't exist, you can create it with just the above lines to override the defaults.  You don't need a full config file.

Config file handling is one of the current pain points in Gargoyle.  Modifying text files is not ideal, but it's how things are done for now.

**Comment by nickbe** [comment]
Maybe we could have different settings within the config and just switch between them either via menu or simply by commandline.

**Comment by cspiegel** [comment]
I think the first step would be to define themes and allow them to be selected by name in the config file.  In this case, a theme would just be a grouping of settings relating to themes (basically, all color options).

As it stands, modifying the config file directly is just how configuration is done in Gargoyle.  I do want there to be a better way to handle it, but it'll take a good bit of effort.

**Comment by ElonSatoshi** [comment]
@cspiegel Thanks for the theme!

You know, maybe we could also have a wiki page listing theme configs such as that, for users to paste into their .garglkrc

**Comment by cspiegel** [comment]
> @cspiegel Thanks for the theme!
> 
> You know, maybe we could also have a wiki page listing theme configs such as that, for users to paste into their .garglkrc

https://github.com/garglk/garglk/wiki/Color-Themes

Things are moving slowly in the right direction.

**Comment by cspiegel** [comment]
I've got some changes in pull request #664 that address this.

You can now select themes using the `theme` option in the configuration file.  Some themes are included, and you can create your own. There are built-in themes called `dark` and `light`, as well as `system`, which attempts to follow the system theme.

See https://github.com/cspiegel/garglk/blob/user-themes/THEMES.md for some (hopefully understandable) documentation on how the themes work.

If you're logged in to GitHub, you can find binaries through the pull request: go to the details of whichever check is relevant for you (e.g. AppImage for Linux users, or MinGW for Windows users), hit the "Summary" links, and builds should be available there.
