### ISSUE TITLE
Freetype problem hinders compile

### ISSUE THREAD

**Issue by AndreasDavour** [garglk/garglk#358]
Simply put, what the heck is freetype.pc and why is it not detected? I do have the freetype packes, including devel packages with headers, installed.

[ante@powerpad garglk]$ jam
OS is LINUX (gtk+) 
BUILD is RELEASE 
...patience...
...found 1816 target(s)...
...updating 505 target(s)...
Cc build/linux.release/garglk/main.o 
Package freetype was not found in the pkg-config search path.
Perhaps you should add the directory containing `freetype.pc'
to the PKG_CONFIG_PATH environment variable
Package 'freetype', required by 'virtual:world', not found
Archive build/linux.release/garglk/libgarglkmain.a 
ar: creating build/linux.release/garglk/libgarglkmain.a
Ranlib build/linux.release/garglk/libgarglkmain.a 
Cc build/linux.release/tads/argize.o 
Cc build/linux.release/tads/bif.o 
^C...interrupted
...updated 3 target(s)...
[ante@powerpad garglk]$ 
[ante@powerpad garglk]$ rpm -qa | grep freetype
freetype-2.9.1-7.fc30.x86_64
freetype-2.9.1-7.fc30.i686
freetype-devel-2.9.1-7.fc30.x86_64

**Comment by cspiegel** [comment]
`.pc` files, along with the `pkg-config` program, are the more-or-less standardized way on Unix platforms to find headers and libraries.  If a `.pc` file isn't found, it typically means that the package that provides it isn't installed.

However, FreeType's `.pc` file is really called `freetype2.pc`, and as far as I can see all the calls to `pkg-config` in the Jam files are asking for `freetype2`, which is to say, I'm not at all sure where `freetype.pc` is coming from for you.

Can you run `jam -dx` and paste the output here, at least the output around the failing bit?  That will display which commands are run, and may help figure out which part of the build is asking for `freetype` vs `freetype2`.

**Comment by AndreasDavour** [comment]
Thanks. I was not aware of the .pc files before. Good to know. 

That was when I had changes a bunch of things around due to other dependencies, but maybe it's better do run from the start. I did a clean clone and ran "jam -dx" and this is how it looks.

[garglk]$ jam -dx
OS is LINUX (gtk+) 
BUILD is RELEASE 

cc -c -o build/linux.release/garglk/main.o `pkg-config freetype2 gtk+-x11-2.0 gdk-x11-2.0 gobject-2.0 glib-2.0 fontconfig libpng zlib sdl SDL_mixer --cflags` -fPIC -std=gnu99 -DGARGLKINI=\"/etc/garglk.ini\" -DGARGLKPRE=\"\" -DGARGLK_USESDL -DBABEL_HANDLER -Isupport/babel -DBUNDLED_FONTS -O2  -Igarglk -Isupport/sdl -Isupport/sdl_sound -Isupport/babel -Igarglk garglk/main.c

Package gtk+-x11-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-x11-2.0.pc'
to the PKG_CONFIG_PATH environment variable
Package 'gtk+-x11-2.0', required by 'virtual:world', not found
Package 'gdk-x11-2.0', required by 'virtual:world', not found

ar ru build/linux.release/garglk/libgarglkmain.a build/linux.release/garglk/main.o
ar: creating build/linux.release/garglk/libgarglkmain.a
ranlib build/linux.release/garglk/libgarglkmain.a
rm -f build/linux.release/garglk/main.o

Here we can see the first dependencies fails. This is on Fedora 30, and I guess this is not the way things are named on Fedora. But, what should they be?

[garglk]$ sudo dnf search gtk+-x11
[sudo] password for: 
Last metadata expiration check: 0:37:32 ago on mån 16 dec 2019 10:45:31.
No matches found.
[garglk]$ sudo dnf search gdk-x11
Last metadata expiration check: 0:37:47 ago on mån 16 dec 2019 10:45:31.
No matches found.

**Comment by cspiegel** [comment]
I'm not familiar with Fedora, but you might try `gtk2-devel` as the package name.  It also looks like `libgtk+-x11-devel` is a valid name on some RPM-based platforms, but I'd assume your search would have turned that up if it were so on yours.

**Comment by AndreasDavour** [comment]
Yeah, in a simple world, those would be the ones, but sadly not. It would be very nice if the build could be a bit more distro independant. 

What are those packages supposed to provide?

**Comment by interactivefiction** [comment]
I have tested the following on Fedora 29/30/31, with these dependencies branch release/2019.1 builds as long as SDL is disabled (jam -sUSESDL=no).  Also, I have found it is also important to be sure the Fedora OS is fully up to date too.

**Development Environment Packages To Install:**

sudo dnf install jam
sudo dnf install freetype-devel
sudo dnf install gcc-c++
sudo dnf install gtk2-devel
sudo dnf install libjpeg-turbo-devel

**Some Optional Source Control Related Packages:**

sudo dnf install git-cola
sudo dnf install PyQt5

If you are mainly interested in using Gargoyle versus building from source for development purposes, I have created an unoffical RPM for 2019.1 release branch.  You can download it here if you would like to try it: https://github.com/interactivefiction/garglk-builds/tree/testbuilds

**Comment by AndreasDavour** [comment]
Thanks! I was primarily interested in using Gargoyle, but as I found this repo with instructions I thought I might as well try to see if the procedure was usable for Fedora, and maybe find a way to make it smooth sailing to compile if for others. 

IF used to be pretty platform independent, and sadly I've found it less so these days.

Compiling with "jam -sUSESDL=no" does seem to work, yes! :)

**Comment by interactivefiction** [comment]
Hopefully, with some effort we can find a way to get SDL to work too :-)

**Comment by cspiegel** [comment]
> Yeah, in a simple world, those would be the ones, but sadly not. It would be very nice if the build could be a bit more distro independant.
> 
> What are those packages supposed to provide?

It is quite distribution-independent: it's using `pkg-config` to find widespread packages in a (de facto) standard way.

Now, Gtk2 and SDL1 are older libraries, so it's possible that they're not packaged in Fedora, though there are probably ways to get them.  At some point I'd like to switch from Gtk2 to Qt5, and from SDL1 to SDL2, but those aren't *huge* priorities at the moment.

SDL is used for sound, and gtk is used for drawing the window and providing dialogs on Unix systems.

**Comment by angstsmurf** [comment]
I haven't checked this, but I think the current SDL sound code will work as-is with SDL2. At least the SDL2 sound code used in Spatterlight is pretty much the same as the code currently in Gargoyle.

**Comment by AndreasDavour** [comment]
I'm pretty sure SDL2 is workable. If some testing can be done to make it more Fedora friendly, just let me know if I can test something.

**Comment by AndreasDavour** [comment]
Also, if someone packaged the Fedora packages wrong, say missing a .pc file, it would be good to figure out.

**Comment by interactivefiction** [comment]
Got an SDL enabled build to go through on Fedora 29 so that Gargoyle will compile with "jam" and no additional parameters.

**SDL Related Build Packages**:

1) sudo dnf install SDL
2) sudo dnf install SDL-devel
3) sudo dnf install SDL_mixer
4) sudo dnf install SDL_sound-devel
5) sudo dnf install SDL_mixer-devel

**Comment by AndreasDavour** [comment]
That does indeed compile fine!

**Comment by AndreasDavour** [comment]
I opened a PR to add these details to the documentation.

**Comment by cspiegel** [comment]
> I haven't checked this, but I think the current SDL sound code will work as-is with SDL2. At least the SDL2 sound code used in Spatterlight is pretty much the same as the code currently in Gargoyle.

When I tried it, the problem I ran into is that SDL_sound has not been ported to SDL2.

But looking into it a bit, SDL_mixer seems to support all audio formats that Blorb needs, and is already being used by Gargoyle for MOD files.  It may be possible to use SDL_mixer for all audio, thus removing the need for SDL_sound and allowing a move to SDL2.

**Comment by angstsmurf** [comment]
In Spatterlight, SDL_sound is built from source (unmodified from Gargoyle) and used along with the official binaries for SDL2 and SDL2_mixer, and it seems to work fine. Actually, I haven't really thought about the fact that this is what I'm doing until you mentioned it now.

**Comment by cspiegel** [comment]
Closing because the bug as written has been addressed, and I've created #376 to address the SDL porting.
