### ISSUE TITLE
Documentation for getting Level 9 games working

### ISSUE THREAD

**Issue by Screwtapello** [garglk/garglk#365]
I recently spent a few hours struggling to get a copy of the Level 9 game "Lancelot" to run properly on Gargoyle, and for the benefit of future generations I'd like to document the process.

What I started with (from the MS-DOS version of the game):

- A bunch of image files, named `1.PIC` up to `30.PIC`, which are displayed during gameplay
- Files named `GAMEDAT1.DAT`, `GAMEDAT2.DAT`, `GAMEDAT3.DAT`, which are the actual game files
- Files named `MENU.EXE` and `MENU.TXT`, which are the original MS-DOS terp

What I had to do:

- Rename `GAMEDAT1.DAT`, etc. to `lancelot1.sna`, etc. because Gargoyle doesn't recognise a Level 9 game unless it ends with `.l9` or `.sna`, and `.l9` didn't work for other reasons
- Rename the image files from `1.PIC`, etc. to `1.pic`, etc. because apparently the Level 9 terp only checks for MS-DOS pictures in lower-case
- Delete the original MS-DOS terp, since it wouldn't work with the renamed files

As a point of comparison, ScummVM has [an excellent wiki page](https://wiki.scummvm.org/index.php/Datafiles) describing what files need to be collected, and how they should be named, for all the various kinds of games it can run. I couldn't find such a thing for Gargoyle, but I feel like there ought to be. Just as a starting point, I'd be happy to make a PR with a `docs/datafiles.md` containing the above information, or write it up on the project wiki or similar.

**Comment by cibersheep** [comment]
Hello.
There's a workaround with gargoyle for some of this behaviour:
- instead of opening the game as `gargoyle GAMEDAT1.DAT` try `level9 GAMEDAT1.DAT` with tell gargoyle to use the level 9 interpreter.

The rest in level9 interpreter github :)

**Comment by cspiegel** [comment]
I think it'd be great to start a document like that.  If you want to write something up and attach it here I can look at how we might organize a Wiki.

I've also been planning (for a while now) to update the launcher to be able to inspect files and determine the proper interpreter based on their contents rather than extension.  This wouldn't be completely seamless (Scott Adams games, for example, will pose an interesting problem).  The issues you ran into with Level 9 games only makes it that much more clear that something like this would be useful.

**Comment by cspiegel** [comment]
For reference, https://github.com/garglk/garglk/blob/master/garglk/launcher.c (near the end of the file) contains the mapping from extension to interpreter, if you want to use that as a starting point.

**Comment by cibersheep** [comment]
Interesting. There's a little tool called babel that helped me with that in [Gelek](https://gitlab.com/cibersheep/gelek) it detects most of files (and the rest can be done with extension)

All information about Babel is [here](http://babel.ifarchive.org/)

And the source is [here](http://babel.ifarchive.org/downloads/babel.zip)

I managed to compile it for different architectures (amd64, armhf and arm64)

**Comment by Screwtapello** [comment]
I've written up a skeleton that should be fairly easy for new IF users to follow, and easy to extend for new formats in the future. Currently it covers the Level 9 information I listed above, plus mentions of HTML, TADS, and Z-machine games to give an idea of how the document might grow:
https://gist.github.com/Screwtapello/18cb7260b7471bd028a161a89a2c0347

Let me know if you spot any inaccuracies, or other problems. I *may* have written too much; feel free to cut things down to size, or otherwise reorganise the information.

> There's a little tool called babel...

I looked at babel, but I don't think it will be much help here. For one, it doesn't seem to automatically package games, it just inspects them. For another, as a command-line tool it's probably more complex than a new IF player is willing to deal with.

**Comment by cibersheep** [comment]
> I've written up a skeleton that should be fairly easy for new IF users to follow

Very nice. I would not advice to use sna though as it is a very well known zx snapshot file type (that's why Gargoyle recognize it as Level 9 game, because it can play zx sna of Level 9 games.
Instead, I will advice to use `level9 [renamed].dat` which will work. `level9` is a shortcut installed with Gargoyle

> > There's a little tool called babel...
> 
> I looked at babel, but I don't think it will be much help here. For one, it doesn't seem to automatically package games, it just inspects them. 

That's why I suggested. You can inspect what type of game is a .xxx file:

```
$ babel -format gamedat1.dat
Format: level9
```

**Comment by Screwtapello** [comment]
At least for the Debian and Arch Linux packages of Gargoyle, only the launcher binary is installed  on `$PATH`; the individual interpreters are tidied away somewhere else. Advising people to run `level9 blah.dat` would just provoke "Command not found" errors.

I agree that `.sna` isn't really appropriate, but so far as I can tell it's the only option that works with the current versions of Level9 and Gargoyle. I'd love to see a cleaner solution (like storing all the game data and graphics in a blorb, or just a wider set of supported file extensions) but I lack the technical skill to make the changes and the political skill to encourage people toward that solution. In the mean time, I think this is the best I can do.

**Comment by cibersheep** [comment]
Interesting. I installed gargoyle and gargoyle-free from the Ubuntu repos (16.04) and I have all the interpreters accessible but I have:
``:~$ ls /usr/lib/gargoyle/
advsys  agility  alan3  bocfel  frotz  geas  git  glulxe  jacl  level9  magnetic  nitfol  scare  scott  tadsr
cibersheep@oem-c16b:~$ ls /usr/games/
adventure   backgammon  cfscores   gargoyle-free   go-fish  level9    number          quiz        scare    tadsr        wtf
advsys      battlestar  countmail  geas            gomoku   magnetic  pacman4console  rain        scott    teachgammon  wump
agility     bcd         cribbage   git             hack     mess      phantasia       random      scummvm  tetris-bsd   zcode-interpreter
alan2       bocfel      dab        glulxe          hangman  mille     pig             residualvm  sky      trek
alan3       boggle      espdiff    gnome-mahjongg  hugo     monop     pom             robots      snake    wargames
arithmetic  caesar      frotz      gnome-mines     hunt     morse     ppt             rot13       snscore  worm
atc         canfield    gargoyle   gnome-sudoku    jacl     nitfol    primes          sail        sol      worms
```

A `which level9` gives me the ones installed under `/usr/games`

**Comment by Screwtapello** [comment]
I don't have an Ubuntu 16.04 machine handy, but [so far as I can tell](https://github.com/garglk/garglk/issues/365) Ubuntu only provides the `gargoyle-free` package, like Debian, so I expect that's who the `/usr/lib/gargoyle` binaries belong to.

The `/usr/games` binaries must belong to the `gargoyle` package, but I can't guess where it came from. Perhaps some third-party package, since `gargoyle-free` was pretty out-of-date when Ubuntu 16.04 was released, and it's even more out-of-date now.

Interestingly, if I'm reading [Gargoyle's `Jamfile` correctly](https://github.com/garglk/garglk/blob/9182b663152ce9a99b6a7bf66fd8bad2013cdc43/Jamfile#L16-L17), it defaults to installing everything in `/usr/local/libexec/libgargoyle`, even the launcher, so nothing is on `$PATH`. However, the [standard `gargoyle.desktop`](https://github.com/garglk/garglk/blob/master/garglk/gargoyle.desktop) doesn't mention a specific executable path, so it expects the launcher to be on `$PATH` somewhere.

**Comment by cibersheep** [comment]
Interesting indeed. I may or may not try to build it... I can't remember it.

Happilly you can `/usr/lib/gargoyle/level9 game` but I understand that's not for every user.

Did I tell you that with the «old» games (the ones that are *.dat + *.hrc + *.cga) you can tar them and run them like `level9 quest.tar`? That would be a very good slolution if that would work with the most modern ones (the ones with *.title, *.pic)

**Comment by cspiegel** [comment]
@Screwtapello I see you've already been making some edits to the Wiki, so feel free to drop your doc in anywhere you see fit.  The wiki, as you may notice, isn't exactly maintained, so anything you can add to improve it is more than welcome.

**Comment by Screwtapello** [comment]
I've added my document as a new wiki-page, added a link to it from the wiki home page, and done a few other little tidy-ups around the place. Let me know if I messed anything up, please!
