### ISSUE TITLE
Remove Nitfol and Frotz

### ISSUE THREAD

**Issue by cspiegel** [garglk/garglk#368]
Nitfol is no longer maintained, and the version included in Gargoyle (the latest, 0.5) is over 20 years old.  In addition, although it appears abandoned, Nitfol also moved to C# after its last C-based release, so even if development picks up again, Gargoyle doesn't support C# (meaning the build system has no way of integrating C# interpreters, even if those interpreters are capable of linking to libgarglk).

Frotz is maintained, but not in a Glk version.  The Glk version was done for Gargoyle and seems to have been maintained essentially as a fork for the last 10 years at least.

As such, I'm proposing the removal of these two interpreters given that Bocfel is maintained, has been the default for the last two releases, and that Nitfolk and Glk Frotz are not receiving any maintenance.

If there are any reasons anybody has for keeping these around, please let me know.

**Comment by curiousdannii** [comment]
David has sounded open to pulling the Glk implementation into the Frotz repository, so if that happens Frotz could be added back again. For now I think it makes sense to remove them.

My only wishlish for Bocfel was that it's source code was in [your repo](https://github.com/cspiegel/bocfel) rather than just the docs.

**Comment by cspiegel** [comment]
> David has sounded open to pulling the Glk implementation into the Frotz repository, so if that happens Frotz could be added back again. For now I think it makes sense to remove them.

That is perfectly reasonable.  I'd have no problem bringing back a maintained version.

> My only wishlish for Bocfel was that it's source code was in [your repo](https://github.com/cspiegel/bocfel) rather than just the docs.

A completely valid wish, and I understand why you're requesting it.  I've thought about mirroring my local Git repository to Github.  I've not made any decisions either way, but I am sympathetic to your request, and will put some more thought into it.
