### ISSUE TITLE
Does Gargoyle have a CLI? If not can a basic one be implemented?

### ISSUE THREAD

**Issue by oblivioncth** [garglk/garglk#370]
As in a way to launch the main exe and specify the interpreter and game script that should be loaded as arguments.

I would like to add some interactive fiction games to a front end I use but the only way that would work is if I can pass command line arguments to Gargoyle to run a specific game from the get-go, because otherwise each game entry in the front end would only be capable of just launching Gargoyle and the game would still have to be loaded manually, more or less defeating the purpose of the frontend altogether 

I've used this project independently for a while and definitely prefer it to everything else I've tried so it would be great if I could use it in my game collection system with said frontend.

**Comment by cibersheep** [comment]
You can defenitively can do it in Linux: you can run `level9 game` to choose Level 9 interpreter and the game you want to play, `frotz game` etc

**Comment by cspiegel** [comment]
Gargoyle already allows you to pass games to it, if that's what you're asking (e.g. `gargoyle zork1.z3`).  It uses the file's extension to determine which interpreter to use.  As @cibersheep mentions, you can directly call an interpreter itself if necessary, bypassing Gargoyle's detection.  Some day Gargoyle will be able to examine a file's contents to choose the interpreter instead of just relying on the extension, but that day is not today...

The main gargoyle binary is nothing more than a launcher for the individual interpreters, which means that if you do call them yourself, you're just doing what Gargoyle does, so that will work fine.

**Comment by oblivioncth** [comment]
> Gargoyle already allows you to pass games to it, if that's what you're asking (e.g. `gargoyle zork1.z3`). It uses the file's extension to determine which interpreter to use. As @cibersheep mentions, you can directly call an interpreter itself if necessary, bypassing Gargoyle's detection. Some day Gargoyle will be able to examine a file's contents to choose the interpreter instead of just relying on the extension, but that day is not today...
> 
> The main gargoyle binary is nothing more than a launcher for the individual interpreters, which means that if you do call them yourself, you're just doing what Gargoyle does, so that will work fine.

I suppose I could have just tried this for myself, but don't have this installed on the machine with the games on it yet and I've been distracted as of late for obvious reasons.

Thanks for the clarification. Detection based on extension is no problem, I just wanted to make sure I could call gargoyle and pass the game as a parameter as an alternative to using the GUI. Again, I probably should have just tried "gargoyle /?", "gargoyle help", etc, or just tested trying to load a game. I was initially hesitant I guess since I saw no mention of a command line interface here or on the advert site for the app so I wasn't sure if there were certain switches I'd need to be aware of if it did have one.

**Comment by cibersheep** [comment]
@cspiegel I guess you know about Babel, right? There's a c++ implementation that is a bit outdated but very useful still. I use to detect the game files in Gelek: https://gitlab.com/cibersheep/gelek-vanilla/-/tree/master/libs/babel

[Caling](https://gitlab.com/cibersheep/gelek-vanilla/-/blob/master/qml/components/GameInfoPopup.qml#L20) `babel -format` it returns the proper format (quite always right)

**Comment by cspiegel** [comment]
@cibersheep Yep, and Gargoyle even makes use of the Babel code to try to get bibliographic data to display in the title bar.  It's just going to be a matter of taking the time to incorporate it into the launcher.

**Comment by cibersheep** [comment]
Aaah, I see. Nice.

Gargoyle has been a great companion for all this time :)
