### ISSUE TITLE
macOS: Gargoyle won't quit on system shutdown

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#373]
When shutting down macOS, open applications will quit automatically if they are well-behaved, or at worst interrupt the shutdown process with a dialog ("Are you sure you want to quit?"). Gargoyle does neither of these, but just sits there, refusing to let the system shut down until it is manually quit by the user.

Also, selecting Quit from the contextual menu on the Gargoyle Dock icon won't work, but that might be a separate bug.

**Comment by cspiegel** [comment]
@angstsmurf I think I fixed this in #545.  If you have a chance, please let me know if it works for you.

**Comment by angstsmurf** [comment]
Yes, it works. Good job!
