### ISSUE TITLE
Error while building: “failed Link build/linux.release/...”

### ISSUE THREAD

**Issue by stormwatch** [garglk/garglk#375]
The OS is Fedora 32. I've followed the instructions in https://github.com/garglk/garglk/blob/e59be074ef715b7d2b6286b32c6b581ae6070a82/INSTALL#L33

From what I gather, the build fails for some of the targets during the linking process

for example:
> Cc build/linux.release/garglk/fontfc.o                                                                                                                         
> SharedLink build/linux.release/garglk/libgarglk.so                                                                                                             
> /usr/bin/ld: build/linux.release/garglk/cgfref.o: in function `glk_fileref_create_temp':                                                                       
> cgfref.c:(.text+0x213): warning: the use of `tempnam' is dangerous, better use `mkstemp'                                                                       
> Link build/linux.release/garglk/gargoyle                                       
> /usr/bin/ld: build/linux.release/garglk/launcher.o:(.bss+0xc00): multiple definition of `tmp'; build/linux.release/garglk/launchgtk.o:(.bss+0x0): first defined
>  here                                                                                                                                                          
> collect2: error: ld returned 1 exit status                                                                                                                     
>                                                                                                                                                                
> cc  -o build/linux.release/garglk/gargoyle  build/linux.release/garglk/launchgtk.o build/linux.release/garglk/launcher.o build/linux.release/garglk/libgarglk.s
> o -lm `pkg-config freetype2 gtk+-x11-2.0 gdk-x11-2.0 gobject-2.0 glib-2.0 fontconfig libpng zlib sdl SDL_mixer --libs` -lSDL_sound                             
>                                                                                                                                                                
> ...failed Link build/linux.release/garglk/gargoyle ...  

or here:
> Link build/linux.release/alan2/alan2                                                                                                                           
> /usr/bin/ld: build/linux.release/alan2/main.o:(.bss+0x1b0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined h
> ere                                                                                                                                                            
> /usr/bin/ld: build/linux.release/alan2/main.o:(.bss+0x1b8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined her
> e                                                                                                                                                              
> /usr/bin/ld: build/linux.release/alan2/debug.o:(.bss+0x0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined he
> re                                                                                                                                                             
> /usr/bin/ld: build/linux.release/alan2/debug.o:(.bss+0x8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined here
> /usr/bin/ld: build/linux.release/alan2/args.o:(.bss+0x0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined her
> e                                                                                                                                                              
> /usr/bin/ld: build/linux.release/alan2/args.o:(.bss+0x8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined here 
> /usr/bin/ld: build/linux.release/alan2/inter.o:(.bss+0x0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined he
> re                                                                                                                                                             
> /usr/bin/ld: build/linux.release/alan2/inter.o:(.bss+0x8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined here
> /usr/bin/ld: build/linux.release/alan2/parse.o:(.bss+0xd8): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined h
> ere                                                                                                                                                            
> /usr/bin/ld: build/linux.release/alan2/parse.o:(.bss+0xe0): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined her
> e                                                                                                                                                              
> /usr/bin/ld: build/linux.release/alan2/rules.o:(.bss+0x0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined he
> re                                                                                                                                                             
> /usr/bin/ld: build/linux.release/alan2/rules.o:(.bss+0x8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined here
> /usr/bin/ld: build/linux.release/alan2/readline.o:(.bss+0x8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined h
> ere                                                                                                                                                            
> /usr/bin/ld: build/linux.release/alan2/readline.o:(.bss+0x0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined
>  here                                                                                                                                                          
> /usr/bin/ld: build/linux.release/alan2/glkstart.o:(.bss+0x8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined h
> ere                                                                                                                                                            
> /usr/bin/ld: build/linux.release/alan2/glkstart.o:(.bss+0x0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined
>  here                                                                                                                                                          
> /usr/bin/ld: build/linux.release/alan2/glkio.o:(.bss+0x8): multiple definition of `glkMainWin'; build/linux.release/alan2/arun.o:(.bss+0x8): first defined here
> /usr/bin/ld: build/linux.release/alan2/glkio.o:(.bss+0x0): multiple definition of `glkStatusWin'; build/linux.release/alan2/arun.o:(.bss+0x0): first defined he
> re                                                                                                                                                             
> collect2: error: ld returned 1 exit status

> cc  -o build/linux.release/alan2/alan2  build/linux.release/alan2/arun.o build/linux.release/alan2/main.o build/linux.release/alan2/debug.o build/linux.release
> /alan2/args.o build/linux.release/alan2/exe.o build/linux.release/alan2/inter.o build/linux.release/alan2/parse.o build/linux.release/alan2/rules.o build/linux
> .release/alan2/stack.o build/linux.release/alan2/decode.o build/linux.release/alan2/term.o build/linux.release/alan2/reverse.o build/linux.release/alan2/readli
> ne.o build/linux.release/alan2/params.o build/linux.release/alan2/sysdep.o build/linux.release/alan2/glkstart.o build/linux.release/alan2/glkio.o build/linux.r
> elease/alan2/alan.version.o build/linux.release/garglk/libgarglkmain.a build/linux.release/garglk/libgarglk.so -lm `pkg-config freetype2 gtk+-x11-2.0 gdk-x11-2
> .0 gobject-2.0 glib-2.0 fontconfig libpng zlib sdl SDL_mixer --libs` -lSDL_sound 
> 
>...failed Link build/linux.release/alan2/alan2 ...

Here is the complete log
[build.log](https://github.com/garglk/garglk/files/4606703/build.log)

**Comment by cspiegel** [comment]
Is this gcc 10?  I haven't installed gcc 10 yet, but I've looked over the release notes, and this looks like gcc being stricter (which is good) about invalid code, and the Alan code is invalid.

I'll install a copy of gcc 10 and, if that's the problem, fix it.

**Comment by cspiegel** [comment]
Please look at #377; I was able to reproduce the problem with gcc10 and fix it.  Let me know if it works for you.

**Comment by stormwatch** [comment]
> Please look at #377; I was able to reproduce the problem with gcc10 and fix it. Let me know if it works for you.

It does! thank you.
