### ISSUE TITLE
Port to SDL2

### ISSUE THREAD

**Issue by cspiegel** [garglk/garglk#376]
Gargoyle currently uses SDL1.  It should be updated to use SDL2 instead.

**Comment by mstoeckl** [comment]
I've attached a patch giving one possible approach for this: [0001-Port-to-SDL2.txt](https://github.com/garglk/garglk/files/5790133/0001-Port-to-SDL2.txt); it only adjusts the build under "Unix", as I don't know what other platforms need and cannot test them.

The only parts of SDL which are used are the Timer API, and SDL_Mixer, neither of which has changed interfaces, so the only code that needs upgrading is that involving SDL_sound. However, recent versions of SDL_Mixer support playing MP3 and OGG files as chunks, so the code paths involving SDL_sound can be excised entirely.

**Comment by angstsmurf** [comment]
I've tested this on macOS and it seems to work flawlessly. I never realised just how much code was included for a single (no longer) missing feature of SDL_Mixer.
