### ISSUE TITLE
Bocfel: Trinity blockquotes get stuck if user resizes window

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#385]
If you resize the Gargoyle window while Trinity displays one of its quotes, making the window wider or narrower, the quote will not disappear the next turn as intended, but stay on-screen until saving, restoring or restarting.

This seems to only occur in Trinity, not in Curses or other Inform games with blockquotes.

This might be related to the "[delayed updates](https://github.com/garglk/garglk/blob/master/terps/bocfel/screen.c#L729-L741)" of the status window in Bocfel.

**Comment by cspiegel** [comment]
Proposal: disallow window resizing.

But seriously, good find.  The whole quote box thing is just a massive headache with Glk, and when combined with window resizing, something the Z-Machine isn't particularly adept at, I shouldn't be surprised there's some breakage!  I think the proper approach here is to simply ignore the delayed upper window code when the resize comes from outside the game, but I'll take some time to look at it in more detail and get a fix in.

**Comment by angstsmurf** [comment]
Yeah, the simple change I pushed to the Spatterlight repro (the one listed here above because it references this issue) seems to work, but I'm sure there are better ways.

**Comment by curiousdannii** [comment]
I've started working on a test suite for upper window quirks (not published yet). I'll have to remember to investigate and try to replicate what Trinity is doing here.

**Comment by cspiegel** [comment]
An upper window tester would be a great tool to have! I had to make do with a bunch of ad hoc tests while I was developing and I wouldn't be surprised if a rigorous tester found some bugs.

**Comment by angstsmurf** [comment]
Closed by #401
