### ISSUE TITLE
Font resolution (macOS)

### ISSUE THREAD

**Issue by onebrownfinch** [garglk/garglk#387]
I was hoping that updating to the 2019 build of Gargoyle would fix the font resolution issues; however, it seems not. Fonts appear fuzzy and messing with the settings doesn't fix it. The closest I've been able to come to a solution is following another user's (#192) tip of doubling the font-related settings. This makes the text readable but so big that I've reverted to the old, fuzzy version. Any advice?

**Comment by angstsmurf** [comment]
I'd suggest trying out this pull request: #364

**Comment by onebrownfinch** [comment]
> I'd suggest trying out this pull request: #364

Thank you! I'm sort of new to git, do I just replace the files in my garglk folder with the updated ones in the pull request and see how it works?

**Comment by angstsmurf** [comment]
In theory, yes. Although there is plenty of Git stuff that might make it easier.

**Comment by angstsmurf** [comment]
Also, if you're on macOS, have you checked out [Spatterlight](https://github.com/angstsmurf/spatterlight)?

**Comment by onebrownfinch** [comment]
Y'know, that logo looks familiar so I must've tried it out when I was getting into IF a couple of years ago, I'll give it a go again!

**Comment by angstsmurf** [comment]
I've resurrected it from an older codebase, but it still needs a lot of testing.

**Comment by onebrownfinch** [comment]
Damn, just gave it a try and I'm loving it! Thanks for resurrecting it, I'll be sure to follow the github page
