### ISSUE TITLE
Bocfel crash, abbreviation-related

### ISSUE THREAD

**Issue by hlabrand** [garglk/garglk#394]
While releasing my latest game, I have discovered that it crashes my old Gargoyle for Linux. The crash also happens on the latest windows release from 2019, but also (one of my players say) on Spatterlight for MacOS. Since it's an in-game message that gets printed, and since Gargoyle and Spatterlight both use Bocfel, it must be a Bocfel error.

In my game, I use the seldom-used full 96 abbreviations for the Z-Machine. (As per the standards, a game can define 96 abbreviated strings; Inform 6 allows you to use 64, and the remaining 32 are called "printing-variables" (page 30 of the Designer's Manual 4), and are defined with a different command; using them makes your source pretty unreadable, so few games, if any, use them.)
The text displays fine for the intro text and the first room, but as soon as you make one or two moves, the game crashes with the message "fatal error: abbreviation being used recursively". Note that none of my abbreviations overlap, and that every other interpreter I have tried (Frotz, but also a lot of different interpreters for older computers) handles them correctly (with the exception of the GameBoy Color interpreter, which just doesn't display them).

I'm attaching a .z3 file, that I had to rename ".txt" for Github. This contains a version of the free demo for my game compiled with these extra 32 abbreviations; you can crash by typing "go south" at the first move. Let me know if I can be of any help.

[tristam-crunch.txt](https://github.com/garglk/garglk/files/5578948/tristam-crunch.txt)

**Comment by cspiegel** [comment]
There is almost certainly something violating the standard in this story, although whether that's the fault of the standard, the fault of Inform, or something else entirely, I'm not sure.

According to §3.3.1 of the Z-machine Standards Document 1.1, "Abbreviation string-printing follows all the rules of this section except that an abbreviation string must not itself use abbreviations".  This story file is using recursive abbrevations contrary to the standard.

To add a few more data points:

* Fizmo exits with "Maximum abbreviation depth is 1".
* Zoom displays, in part, the string "The horizon &nbsp; bare" which I assume is related to the abbreviation issue.
* txd (the disassembler) give a diagnostic of "Warning: printing of non-existent string" while disassembling, and the offending line in the disassembly points to a string which txd decodes as "You trudge uncomfortab &nbsp;  into the &nbsp;  ld water, and try to look a you. The horizon  &nbsp;  bare, and the island looms beh  &nbsp;  you; you can see ".

I don't know the reasoning behind disallowing recursive abbreviations, and Bocfel appears to handle them just fine if I remove the assertion.  Are you able to provide source code for a minimal program which causes this behavior?  I'd like to see what's going on with Inform to create recursive abbreviations.

**Comment by hlabrand** [comment]
My sincerest apologies... I was sure my abbreviations were disjoint from each other, but there was indeed one abbreviation that contained another one. Sorry, I should have been more careful!

I think the "Abbreviate" command isn't enough to trigger this bug, as the way it replaces strings doesn't create this. However, Abbreviate only allows you to use 64 or the 96 abbreviations. So, the way you can create code that violates the standard is very easy:

```
Abbreviate "@00 Smith";

[ Initialise ;
    string 0 "John";
];
```

This is allowed by Inform 6... perhaps it shouldn't be :) I haven't tried to see if one can write `string 01 "@00 Wayne"`, but I can see these kinds of statements being risky and disallowed.

**Comment by cspiegel** [comment]
No problem!  It does seem that Inform ought to disallow the use of a printing variable (which I assume is implemented as an abbreviation) inside of an abbreviation statement.  Unlike many other things that can cause crashes, this can be caught at compile time.

**Comment by hlabrand** [comment]
Yep! I asked at the Inform 6 repository :)

So I don't really know if you need to deactivate that warning on 
Gargoyle's code. Seems like if recursion is allowed I could create 
(voluntarily, I suppose...) some nasty patterns that'd make the game not 
work very well. Anyway, I'm probably the only person ever to use that 
many abbreviations in I6...

Le 24/11/2020 à 13:29, Chris Spiegel a écrit :
> No problem!  It does seem that Inform ought to disallow the use of a printing variable (which I assume is implemented as an abbreviation) inside of an abbreviation statement.  Unlike many other things that can cause crashes, this can be caught at compile time.
>

**Comment by cspiegel** [comment]
I took a quick look and it's trivial to create a real problem:

```
[Main;
  string 0 "@01";
  string 1 "@00";

  print "@00";
];
```

This causes Frotz and Zoom to crash with a segfault (due to excessive recursion) and Viola to abort with a `RecursionError` exception.  It would be easy to add a recursion depth test, but I think the standard disallowing nested abbreviations does make the most sense.

I'll close this ticket for now since Bocfel is behaving according to the spec (and as an extra data point, at least Fizmo and Nitfol explicitly disallow nested abbrevations as well).
