### ISSUE TITLE
MOD music loop bug

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#396]
I'll just report it here as I can't seem to fix it myself: When playing MOD music, the current SDL sound code in Gargoyle plays music once when it is told to play it twice, i.e. repetitions is set to 2. It works correctly for 1 and 3 repetitions, but fails for 2. (This may be confusing: remember that 1 repetition means play the sound once, 0 repetitions means play nothing at all etc.)

It works as it should when playing OGG or AIFF sounds. It also works correctly in Spatterlight with pretty much identical code, which makes me suspect that this is a bug in SDL 1, or rather in the Mikmod library that SDL 1 uses for MODs. (Spatterlight uses SDL 2.)

This can be tested with the [Sound Test](https://github.com/angstsmurf/soundtest/releases) program. Just >SET LOOPS TO 2 and >PLAY MOD. Compare with >LOOP 1. (I know that the default songs are on the long side, which quickly becomes annoying. I took the shortest loopable non-copyrighted sounds I could find.)

**Comment by cspiegel** [comment]
I tested with the latest build that uses SDL2, and from what I can see, the loop bug is still there.  Would you be willing to test and verify that?  I want to be sure I'm doing it right.

If the bug is still occurring, I'll take a look and see if I can figure out what's happening.

**Comment by angstsmurf** [comment]
I think this can be fixed by removing `- 1` at [line 638](https://github.com/garglk/garglk/blob/master/garglk/sndsdl.c#L638) in `sndsdl.c`, so that the line is just `loop = chan->loop;`.

A bit embarrassing, especially as I'm pretty sure I tested this when reporting the bug.

I can make this a PR if you want.
