### ISSUE TITLE
(linux mint) Dark mode?

### ISSUE THREAD

**Issue by mushroomtaste** [garglk/garglk#413]
(sorry if this post isn't optimised I'm new to github)

I love the speed of this program but my only issue is that I can't find an option for changing text/background/highlight colours like gluxe and the bright white hurts my eyes. 

(I'm using the free version from linux mint package manager.)

**Comment by curiousdannii** [comment]
You can change the colours in garglk.ini: https://github.com/garglk/garglk/blob/master/garglk/garglk.ini

**Comment by mushroomtaste** [comment]
Thankyou is just what I needed
