### ISSUE TITLE
macOS build script needs to be updated for Big Sur

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#420]
The current build script for macOS, `gargoyle_osx.sh`, won't detect OS 11 Big Sur properly.

The problem is the regex on line 21:
```
case $SDK_VERSION in
  *10.1[4-9]* )
```

It could be changed to something like
```
  *10.1[4-9]*|*11.* )
```
but ideally into something that will correctly detect a future OS 12 and so on. `*10.1[4-9]*|*1[1-9].*`? I'm not great at regular expressions.

@erkyrath Do you have time to take a look at this?

**Comment by erkyrath** [comment]
Sure.

**Comment by erkyrath** [comment]
(This is actually a glob, not a regex! Ah, shell fun.)

**Comment by angstsmurf** [comment]
Fixed by #422
