### ISSUE TITLE
Proposed Configuration Option: Font LCD Antialiasing Filter

### ISSUE THREAD

**Issue by Tynach** [garglk/garglk#432]
In preparation for implementing linear alpha blending (correctly implemented gamma-correct text rendering), I'd like to also implement a setting for choosing what antialiasing filter to have FreeType use.

Currently, Gargoyle does its own filtering. However, FreeType has its own filtering system that is likely to be better-optimized (or at the very least, will prevent Gargoyle from having to do the processing itself). This filtering system behaves extremely similarly to Gargoyle's when given the same numbers as Gargoyle uses for its own filtering; in fact, the only differences I can visibly see are that Gargoyle's filter cuts off the rightmost pixel sometimes (not usually; it's kinda rare and I don't know a reliable way to reproduce).

However, FreeType *also* has several presets that you can choose from without having to manually send it each value of the 5-tap filter. These are:

0. **None**: No filtering takes place. Used to be the default if you didn't remember to select one, before version 2.10.3.
1. **Default**: This is actually rather similar to Gargoyle's filter, but a bit sharper - juuust enough to be noticeable. Might have more color fringes than Gargoyle's filter when gamma correction is not used, but looks fine otherwise. Most Linux distros use this by default already.
2. **Light**: A technically correct 'boxy' filter. This one will have rather severe color fringing artifacts, unless you use gamma correct rendering... At which point if the display gamma is exactly matched, it will be the absolute sharpest, cleanest, and best looking filter possible. If the gamma correction *doesn't* exactly match the real display's gamma, there might still be either apparent differences in stem widths for the drawn glyphs, or some random color fringes sprinkled throughout. Both issues can range from, "What are you talking about, I ain't never seen any of that!" to, "I sometimes notice it just slightly, and when I do it BUGS ME."
3. **Legacy**: Ultrasharp and ultracolorfringy filter inherited from some old Cairo code. Doesn't actually use the same filtering code, does some other processing to do the filtering. Kinda ugly looking, but some people *like* that sort of ugly.

So, here's the issue... I'd like to make this configurable, because different people will prefer different things. If you don't want color fringes, but you also don't want gamma correction, Gargoyle's current filter is actually really nice! But to have FreeType filter things with it for us (instead of Gargoyle doing it manually after the fact), it has to be passed in as a set of 5 numbers. To be exact, those 5 numbers are `28, 56, 85, 56, 28`.

(By the way, FreeType recommends using just 3 numbers and arranging them symmetrically like that, which is just fine because Gargoyle behaves that way anyway.)

What I'd like to propose is 2 new config options: an option to choose one of the presets using 0-3, or either -1 or something like 8 for choosing 'custom' - at which point the second option is parsed, that being a set of 5 numbers in the range of 0 to 255, which are then directly passed into it as filter weights.

To maintain the appearance of text with the default settings, and because it's honestly not a bad set of defaults, the default setting for the first one would be whatever represents 'custom', and the default setting for the second one would be Gargoyle's current filter weights (as given above).

However, the main problem is that I don't see how to set 5 numbers using the configuration code. Looking at `garglk/config.c`, I see a lot of things being set into arrays of 3 numbers, but not 5. I also see some very specialized ones, so I know there's probably a way to do this, but I feel like there might be some sort of preferred way to go about this to make it more uniform with other options.

Additionally, I don't know if I'm overthinking this. @cspiegel has seen what Gargoyle looks like with FreeType's default filter instead of Gargoyle's, and has said it looks much sharper. Honestly, I agree, and the default filter *is* well-suited for both use with and without gamma-corrected linear alpha blending. I personally waffle a bit between using FreeType's 'default' and 'light' filters; I find that both have merits, and I don't know which I prefer.

Maybe it would be an overall good thing to just use the default filter, and if people want to do anything custom they'll have to edit the code themselves. It'd be much simpler to code, after all.

On the other hand, I have this compulsion to make *everything* an option (yes, I'm a KDE user), and I've already written all the code for this except for the code to set the filter with 5 user-configurable numbers. It just feels incomplete without that to me, though.
___

I'm also awfully sleepy. I think I probably rambled a bit much there and didn't word things very well, not to mention submitting the issue early by accident. Sorry if this is a confusing mass of words; I'll answer any questions anyone might have, even if it's just an overwhelmed 'Whaat??' - in the morning I should be more capable of making sense.

**Comment by Tynach** [comment]
Actually, I'm thinking that any *invalid* option (anything other than 0, 1, 2, 3, or 16 (3 and 16 being equivalent); these are the numeric values for the options in the `FT_LcdFilter` enum) should result in the 'custom' value. I suppose `-1` works as a default that should never clash with future LCD filter presets.

**Comment by Tynach** [comment]
Actually, I'm thinking that any *invalid* option (anything other than 0, 1, 2, 3, or 16 (3 and 16 being equivalent); these are the numeric values for the options in the `FT_LcdFilter` enum) should result in the 'custom' value. I suppose `-1` works as a default that should never clash with future LCD filter presets.

Alternatively, I could look for the literal words 'none', 'default', 'light', 'legacy', or 'custom'. This might be more human-readable.

@cspiegel, any thoughts on this, or how to go about getting 5 integer values from the ini file?

**Comment by Tynach** [comment]
1. Foo

2. Bar

**Comment by Tynach** [comment]
I figured out what'd been going wrong. Lines 255 to 266 of `config.c` selectively only allow certain commands to use more than 1 or 2 arguments, by having the default (in the `else` clause) set of characters to stop parsing at include '` `' (a space). I've added a case for `lcdweights`, and submitted a pull request.

**Comment by cspiegel** [comment]
> Alternatively, I could look for the literal words 'none', 'default', 'light', 'legacy', or 'custom'. This might be more human-readable.

This is what I'd recommend.  It's a bit nicer to avoid magic numbers, and especially to avoid something tied to the internals of Freetype (not that it really matters much, since we're tying ourselves to it with these human-readable names, as well, but it's the principle of the thing).

And in fact I started poking at the code before I saw the issue linked here, and I implemented the human-readable names before I read that you had the same idea.  So if you don't mind, I'll shortly have a pull request into your branch that you can take a look at as suggestions.

**Comment by Tynach** [comment]
> This is what I'd recommend. It's a bit nicer to avoid magic numbers, and especially to avoid something tied to the internals of Freetype (not that it really matters much, since we're tying ourselves to it with these human-readable names, as well, but it's the principle of the thing).

Understood :) I mostly went with the numeric options because that's how the `lcd`, `justify`, `quotes`, and a few other options are. Still, I wasn't sure if that was just how those always were and were kept that way for backwards compatibility, or if it was the preferred style of creating settings.

> And in fact I started poking at the code before I saw the issue linked here, and I implemented the human-readable names before I read that you had the same idea. So if you don't mind, I'll shortly have a pull request into your branch that you can take a look at as suggestions.

I'll go take a look! I think there might be some discussion about that still, such as whether or not to use the same textual names as FontConfig.

**Comment by Tynach** [comment]
Implemented with pull request #433, which is now merged.
