### ISSUE TITLE
macOS builds will not open AdvSys games

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#498]
AdvSys games use a .dat extension, but the Mac version of Gargoyle won't open these. It seems the [Mac-specific code ](https://github.com/garglk/garglk/blob/master/garglk/launchmac.m#L815-L822) gets the allowed file types from the file [launcher.plist](https://github.com/garglk/garglk/blob/master/garglk/launcher.plist), which does not contain an entry for AdvSys games.

**Comment by cspiegel** [comment]
Do you know if plist files do some sort of global registration of extensions?  It's possible .dat files were left off intentionally because of the incredibly generic name; if Gargoyle becomes associated globally with .dat files it would be a bad thing.

**Comment by angstsmurf** [comment]
Yes, they do. The obvious workaround would be to add "dat" (and perhaps "sna" as well) to the `filterTypes` array after reading the others from the plist.

**Comment by cspiegel** [comment]
Done
