### ISSUE TITLE
speech-dispatcher treated as required by cmake, even though it’s not

### ISSUE THREAD

**Issue by huftis** [garglk/garglk#506]
When compiling Gargoyle using cmake, the `cmake` command fails if the optional speech-dispatcher package is not installed:

```
-- Checking for module 'speech-dispatcher'
--   Package 'speech-dispatcher', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:554 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:776 (_pkg_check_modules_internal)
  garglk/CMakeLists.txt:142 (pkg_check_modules)
```

To make it work, it turned out that I had to add `-DWITH_TTS=OFF` to the command line (which is far from obvious from the error message).

Since speech-dispatcher is not really required for Gargoyle to work, it would be much less confusing if speech-dispatcher would be made optional (by default). So if the package was available, it would be automatically enabled, and if not, it would be automatically disabled.

**Comment by cspiegel** [comment]
That's a reasonable request.  I've got a tentative fix in the branch `speech-dispatcher-optional` at https://github.com/cspiegel/garglk.  Let me know if this works for you.

If no TTS option is passed, speech-dispatcher is searched for and used if found, but if it's not found, the build will proceed without TTS support.

If TTS is explicitly requested, the build will fail if speech-dispatcher is not found.
