### ISSUE TITLE
Generate logs

### ISSUE THREAD

**Issue by nulani38728** [garglk/garglk#510]
An interesting feature I'd like to recommend and that I've seen in some other IF players is the ability to write to a text file a log of the content that's been printed to the screen so far. This would allow you to "record" your session and parse the logs in real-time or after the fact. One use case would be integration with a tool like [trizbort](https://github.com/JasonLautzenheiser/trizbort), which draws an automap of your visited locations as you proceed. You could also achieve this by parsing the file yourself and generating PlantUML diagrams to make a map, query dialogue for certain strings, et cetera. Also could be used for posterity, "reading" through your past playthrough, walkthroughs, etc.

E.g.,
```
> log on 
Logging output to somefile.txt
> look
You see a tall, white building.
> log off
Stopped logging
$ cat somefile.txt
You see a tall, white building.
```
The log just contains a verbatim record of the text printed, with the parsing being the obligation of the user.

Apologies if there is already such a feature; I couldn't find a detailed command list.

**Comment by curiousdannii** [comment]
Most interpreters should already support this. Have you found one that doesn't?

**Comment by nulani38728** [comment]
I was trying a .gblorb file, so I assume the application selected git or glulxe. I could not find any documentation about native commands in this or other formats aside from basic save/quit/restore/help commands. Where would I find a detailed explanation of the internal commands exposed by different interpreters?

The trizbort documentation states that Gargoyle is fully compatible with live automapping...

A-ha! I think the magic word is `SCRIPT`. I had to clone the repo and grep for a list of commands like `SAVE` and `QUIT` until I found a mention of the SCRIPT/UNSCRIPT adjacent to those.

I guess this isn't Gargoyle's responsibility if the interpreters define it, but it seems like it should be glossed somewhere. It seems odd that the various interpreters bury that information, and the READMEs in some of the games I launched didn't include any mention of that, either. I guess this is one of those things players are assumed to already know?

**Comment by curiousdannii** [comment]
> I guess this is one of those things players are assumed to already know?

Yeah that's true. And it's probably one of the commands that is least likely to be documented by authors.

A meta command that started a transcript in all interpreters would in theory be possible. With a slash like `/script`. I don't know if Garglk currently has anything like that though.
