### ISSUE TITLE
Building on Apple Silicon?

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#522]
Has anyone been able to successfully build Gargoyle on Apple Silicon (arm64) using Homebrew? If I understand the error messages right, running `make` on an M1 Mac builds Gargoyle for x86_64 and then fails when trying to link with SDL libraries for arm64.

EDIT: The same goes for running the `gargoyle_osx.sh` script.

**Comment by angstsmurf** [comment]
Adding `path=('"/opt/homebrew/lib' $path)` seems to have partly fixed this. `/opt/homebrew`, `/opt/homebrew/bin` and `/opt/homebrew/sbin` were in $path already, but the /lib subdirectory was missing.

Now the last hurdle is that it tries to link `/Library/Frameworks/freetype.framework`, which apparently is Intel only. Is there a way to make Gargoyle use `/opt/homebrew/lib/libfreetype.dylib` instead? Or to install an ARM version into `/Library/Frameworks/` without breaking things?

**Comment by erkyrath** [comment]
> Now the last hurdle is that it tries to link /Library/Frameworks/freetype.framework, which apparently is Intel only.

This must have been installed by some (not-yet-universal) app that you installed. In theory you could uninstall it, if you didn't care about whatever app is relying on it.

I agree there should be a way to make the build process look at /opt/homebrew, but I don't know what paths control that stuff.

**Comment by erkyrath** [comment]
Setting your execution path to include /opt/homebrew/lib also seems wrong -- there's no executable programs in there, right? I suspect there's an actual library path setting which we're missing.

**Comment by angstsmurf** [comment]
Yes, you are right. I wonder if it was something else I tried that was the actual reason it started to work.

After removing the freetype.framework I actually managed to build Gargoyle once, but it crashed immediately with an Invalid signature error. Then I realized that I was not on the master branch, so I checked out that, and now it won't build again, even though the gargoyle_osx.sh file is identical.

**Comment by angstsmurf** [comment]
It works! And with the original, unmodified `gargoyle_osx.sh`!

All I had to do was reinstall cmake with Homebrew. Apparently I was running an old Intel cmake, which was happy to compile to arm64, but refused to link to anything not in `/usr/local/lib/`.

So the necessary steps were:
- Install cmake with Homebrew
- Remove Intel FreeType.framework from /Library/Frameworks
- Re-sign the resulting app with `codesign -o runtime --deep --sign "$CERT_NAME" -fv /Users/administrator/garglk/Gargoyle.app

And thats it.
