### ISSUE TITLE
Saving doesn’t work anymore

### ISSUE THREAD

**Issue by huftis** [garglk/garglk#539]
With the latest Git version, saving doesn’t work anymore. When I try the ‘save’ command in a game (I have tested .z5 and .zblorb games) and enter a file name, the following error message is shown at the bottom of the screen and no file is saved:

    Warning: unable to open save file

Using `git bisect`, I have narrowed the bug down to this commit: 8191cf7dba9de7eaefda06e665104e9c301ff9c6 (*Remove a potentially problematic usage of snprintf()*)

In builds made from this or later commits, saving doesn’t work. In earlier builds, saving works.

**Comment by cspiegel** [comment]
That's a rather nasty bug!  Too bad I replaced “potentially problematic” code with “definitely problematic” code...

Thanks for tracking down the commit.  It made fixing this really easy. I've fixed it in 0db538c if you want to give it a test.

**Comment by huftis** [comment]
Thank you, @cspiegel. I can confirm that both saving and loading are working correctly now.
