### ISSUE TITLE
Broken image loading on some macOS builds

### ISSUE THREAD

**Issue by cspiegel** [garglk/garglk#556]
Some macOS builds display a problem with loading images (at least from Blorb files).

To reproduce, download [Sensory  Jam](https://www.eblong.com/zarf/glulx/sensory.blb) and start it.

First, run `x scroll`, and the result is:

“[Image resource 5 could not be found.]”

Next: `e. x photo`

At this point Gargoye freezes up.

This appears to be present in all builds done by Github actions.  I personally can't reproduce this when I build locally on either Big Sur or Monterey (all images work), but it happens on both Big Sur and Monterey when built via Github actions.

Data point: it seems that PNG files get the "could not be loaded" messages while JPEGs cause things to lock up.  I've run under Valgrind and Address Santizier on Linux to see if there's some memory issues resulting in undefined behavior, but it all looks good.

Because I can't reproduce this locally, it's more or less impossible for me to debug.  I'm at a loss as to what's happening.  @angstsmurf  has bisected this to the switch over to CMake, so there is likely something slightly different occurring during the build, but I don't have the first clue what, especially since the image loading code is the same after the switch to CMake.

**Comment by angstsmurf** [comment]
Console output when failing to show a JPEG image: `Wrong JPEG library version: library is 90, caller expects 80`.

**Comment by cspiegel** [comment]
Thanks for tracking this down!  This fixes it for me as well.  Pull request at #557 which can be tested if you'd like, though you obviously already _have_ tested this change.

**Comment by angstsmurf** [comment]
Seems to work fine!
