### ISSUE TITLE
Windows: Nightly build opens a command prompt window when I launch Gargoyle

### ISSUE THREAD

**Issue by dfabulich** [garglk/garglk#581]
When I go here https://nightly.link/garglk/garglk/workflows/mingw/master and download https://nightly.link/garglk/garglk/workflows/mingw/master/Gargoyle-x86_64.zip run the installer and launch Gargoyle, it opens a black "Gargoyle" command prompt window behind the main window. This is a regression from Gargoyle 2019.1.1.
<img width="2056" alt="Screen Shot 2021-12-02 at 3 00 08 PM" src="https://user-images.githubusercontent.com/96150/144516678-047d8bd9-0b94-4488-94ed-7fc15ca7e279.png">

**Comment by cspiegel** [comment]
Thanks for the report!  I just merged a change into master which ought to fix this.
