### ISSUE TITLE
Apple Silicon (ARM) support

### ISSUE THREAD

**Issue by dfabulich** [garglk/garglk#582]
All modern Macs now ship with "Apple Silicon" ARM CPUs. There should be a Gargoyle build for macOS ARM.

**Comment by angstsmurf** [comment]
I can build an ARM Mac version if anyone is interested.

**Comment by cspiegel** [comment]
@angstsmurf That would be great.  For the release version, at least, I'd like to support as many operating systems as possible.

I'm not sure how easy it is to cross compile to ARM from Intel, which would be necessary for the CI builds to include ARM versions.  If it's not hard, I can add ARM to the CI as well.

**Comment by hkleinsorgen** [comment]
Building Gargoyle with Homebrew for M1 Macs is a bit more difficult because the code must be signed. Without signing you will just see this error:
```
Exception Type:        EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Codes:       UNKNOWN_0x32 at 0x000000010483c000
Exception Codes:       0x0000000000000032, 0x000000010483c000
Exception Note:        EXC_CORPSE_NOTIFY
```

**Comment by dfabulich** [comment]
Huh? You can absolutely build and run unsigned native apps locally on M1 macs. Why is this happening just for Gargoyle?!

**Comment by hkleinsorgen** [comment]
I have seen some linker warnings related to Homebrew libs that lose their signature due to modifications. Might be enough to remove the broken lib signatures from the app.

**Comment by cspiegel** [comment]
The 2022.1 release contains an ARM build for Mac, thanks to @angstsmurf!
