### ISSUE TITLE
Nightly build version self-identifies as 2019.1

### ISSUE THREAD

**Issue by dfabulich** [garglk/garglk#584]
All of the Gargoyle nightly builds have filenames that mention 2019.1, but worse, on macOS, if you go to the Gargoyle --> About menu, it identifies itself as 2019.1.

**Comment by cspiegel** [comment]
Good point.

Pull request #586 switches to use the current date plus git revision as the version for CI builds.

This will require release builds to be done manually, instead of pulling out artifacts from release branches, but that was always the intent.
