### ISSUE TITLE
Couldn't run gargoyle from gargoyle_20211207.7959012-1.deb

### ISSUE THREAD

**Issue by selkieTG** [garglk/garglk#598]
After installation on PopOS (a Debian/Ubuntu derivative), gargoyle failed to load because of an unmet dependency:
$ gargoyle
gargoyle: error while loading shared libraries: libSDL2_mixer-2.0.so.0: cannot open shared object file: No such file or directory

By manually installing via
apt install libsdl2-mixer-2.0-0
the new release loaded up. I wonder if this means there's a missing dependency in the .deb file?

**Comment by cspiegel** [comment]
In fact, there were multiple missing dependencies!  Dependency detection wasn't checking the shared libgarglk which is what actually links against all the required libraries.

https://github.com/cspiegel/garglk/actions/runs/1564720495 has a build which should have all dependencies if you'd like to test; and there is a pull request at #599 with the fix.
