### ISSUE TITLE
Linux releases?

### ISSUE THREAD

**Issue by goodevilgenius** [garglk/garglk#604]
The releases page only shows builds for Windows and macOS, but there appear to be AppImage, Deb, and rpm builds being made. Are they available somewhere?

**Comment by cibersheep** [comment]
I found this git recently: https://github.com/interactivefiction/garglk-builds
Use carefully, I don't know where it comes from

**Comment by cspiegel** [comment]
> The releases page only shows builds for Windows and macOS, but there appear to be AppImage, Deb, and rpm builds being made. Are they available somewhere?

These builds were added after the last release.  You can get up-to-the-minute versions from https://github.com/garglk/garglk/actions (though you have to be logged into Github to download the artifacts there).

The next release (which is imminent, really, truly!) will include the AppImage for Linux, but I'm not sure about the RPM and DEB files.  Ideally those would be provided by distributions.  The builds here are really just for testing.

**Comment by goodevilgenius** [comment]
@cspiegel Cool. No problem grabbing from the artifacts. AppImage is perfectly fine with me.

**Comment by cibersheep** [comment]
Awesome. I didn't know about Actions.
I have tried the deb as well and it's all good for now. Obviously, AppImage is more than good :)

Thanks
