### ISSUE TITLE
Changed code signature in Gargoyle MacOS version 2022.01? 

### ISSUE THREAD

**Issue by suschizu** [garglk/garglk#611]
Hello - I've received a warning that the code signature has changed in the latest MacOS releases:
https://github.com/garglk/garglk/releases/download/2022.1/gargoyle-2022.1-mac-intel.dmg
https://github.com/garglk/garglk/releases/download/2022.1/gargoyle-2022.1-mac-arm64.dmg

`EXPECTED Andrew Plotkin (BK75QRDQ9E) but FOUND Petter Sjolund (6U7YY3724Y)`

Can you confirm this? Thanks!

**Comment by cspiegel** [comment]
This is the first release that supports ARM (i.e. Apple Silicon).  2019.1 was Intel only.  Andrew Plotkin did the Intel builds for both 2019.1 and 2022.1.  Petter Sjolund did the ARM build for 2022.1.

I'm not really familiar with this situation, but it sounds like you're on Apple Silicon, upgrading from 2019.1 to 2022.1?  If that's the case, you were using the Intel build earlier, by Andrew, but are now using the Apple Silicon build, from Petter.  If that describes what happened, then yes, it is expected that the signature has changed.

**Comment by suschizu** [comment]
perfect thanks for the fast answer @cspiegel  - yes - I can confirm that the the ARM build contains the code signature Petter Sjolund (6U7YY3724Y) and the Intel build Andrew Plotkin (BK75QRDQ9E)  🙌
