### ISSUE TITLE
Provide glkunix_fileref_get_filename

### ISSUE THREAD

**Issue by cspiegel** [garglk/garglk#629]
Gargoyle has an API function called `garglk_fileref_get_name` which has been added to remglk under the name `glkunix_fileref_get_filename`

Gargoyle should add this new name, and deprecate the old Gargoyle-specific name.  In addition, it should signal the existence of this function with the `GLKUNIX_FILEREF_GET_FILENAME` macro.

**Comment by cspiegel** [comment]
@curiousdannii Since you're documenting Gargoyle extensions, you'll probably be interested in this issue.  Does it make sense from your perspective to deprecate the Gargoyle-specific name and switch to the one Zarf's got in remglk?  I can't see any downsides, but I may be wrong.

**Comment by curiousdannii** [comment]
The garglk function is present in far more interpreter codebases already. In fact I'm not sure that anything uses the glkunix function yet. I've edited TADS to look for the glkunix function if it can't find the garglk one, and then to map the garglk function name to the glkunix function definition. That seems simpler, at least for existing terps. A new one should probably use the glkunix function?

Garglk should be able to provide both functions. But I wouldn't to so far as to replace all the uses of the garglk function.

**Comment by cspiegel** [comment]
Are there any independent interpreters which use it?  Gargoyle's got some patched interpreters to allow it, but are there any outside interpreters which do?  Bocfel does but that doesn't count since I'll just make any changes necessary there.

Since Spatterlight uses the same interpreters, the function is also exposed there, but that's a bit of a special case: this is more of a burden on a Glk maintainer rather than interpreters (since Petter would have to modify Spatterlight's Glk code if he pulls in modified interpreters).

But since Gargoyle's extension has been "standardized", so to speak, you've convinced me that it ought to continue to exist, as it's not hurting anybody.  It might still be worth marking as deprecated with `__attribute__((__deprecated__))` in the off chance that anybody is building their interpreters against Gargoyle directly, but with no actual plans for removal.

**Comment by curiousdannii** [comment]
Emglken uses Remglk, but the only terp I've ported so far that uses the function is TADS, which we're now maintaining in its own repo. If I was to use more terps from the garglk repo that need the function I'd probably revert to my hacky solution of patching between the functions in Emglken.

I have a vague memory of seeing that Windows Glk had a similar function with a third name, but that's probably not being used by anything currently.

**Comment by cspiegel** [comment]
Done in #631.
