### ISSUE TITLE
How to read the game's output in real time?

### ISSUE THREAD

**Issue by MorenK1** [garglk/garglk#632]
My question's core is how can i read the output of a game to feed it into a script that handles something else, eg. a python script that reacts to a word being printed on screen?

My issue specifically is that i want to script around some events in a .gblorb game, which from what i can see in Window's Task Manager is interpreted by Gargoyle by using git.exe

I found that git has a `SCRIPT` command but its output is inconsistent and laggy, often cutting paragraphs in half and printing out in batches. Perfect for transcripts, not for real time scripting

And i can't find anything else about git's transcript function 

Does Gargoyle have anything to aid me in this? or has anyone tried something similar?

**Comment by cibersheep** [comment]
I know very little but this might be a job for [remglk](https://github.com/erkyrath/remglk/)
I use it for a project and you can send and receive messages throught `stdio`

https://gitlab.com/cibersheep/gelek-vanilla/-/blob/master/plugins/GelekBackend/gelekbackend.cpp#L119

**Comment by cspiegel** [comment]
Somehow you and another person discovered the same bug at approximately the same time (see #633).  Gargoyle _should_ be updating transcripts in real time, but there's a bug preventing it from doing so.  I've got a fix ready, and should have it merged in shortly, but as @cibersheep says, this may be more suited for another Glk implementation, if you don't need the interface of Gargoyle.  If you do need the interface, the fix should be in soon barring any issues.

**Comment by cspiegel** [comment]
OK, for Windows, there are new builds of the release branch here: https://github.com/garglk/garglk/actions/runs/2023857054

This contains a transcript fix, as well as a few other fixes that have been added since the 2022.1 release. The master branch has also been updated with the fix.

**Comment by cspiegel** [comment]
Fixed in #634.
