### ISSUE TITLE
Real time transcript

### ISSUE THREAD

**Issue by Lysandus86** [garglk/garglk#633]
I want to use the Automap in Trizbort, but the transcript file will only update after I close the program. This either seems like something that needs to be implemented with priority, as a lot of people are using some sort of automap with these games, or something wrong with my version of the program.
Trizbort says that Gargoyle is supported, so i'm kinda bummed why it doesn't properly work on my end.

**Comment by Lysandus86** [comment]
Just tested it now and works as intended. Thanks for the quick fix!

**Comment by cspiegel** [comment]
Fixed in #634.
