### ISSUE TITLE
Flatpak Packaging

### ISSUE THREAD

**Issue by Aman9das** [garglk/garglk#638]
Hello, it would be amazing if the app is packaged as a flatpak, I have experience in packaging as flatpak, would the devs be interested in maintaining it after the fact if I help package (just rebase to new commit no. on each release, or put "stable" tag to each release)

**Comment by cspiegel** [comment]
I've got a [Flatpak manifest](https://github.com/garglk/garglk/files/8363620/io.github.garglk.Gargoyle.txt) that I plan on using to eventually put Gargoyle on Flathub.  The only change that should be needed is the source (right now I just have it building from a local directory).

There's a sticking point, though: according to the [app requirements](https://github.com/flathub/flathub/wiki/App-Requirements#application-icons), 64x64 and 128x128 application icons must be available, and all Gargoyle has is a 32x32 icon.  Issue #614 exists for this, with no current resolution.  Once that's done it should be easy enough to get things up and running.

**Comment by cspiegel** [comment]
> I am getting this error, is there a known workaround for it?

Gargoyle needs to be built in a separate directory, so `modules.builddir` needs to be set to true.

**Comment by Aman9das** [comment]
How is this? 
![image](https://user-images.githubusercontent.com/39594914/160424476-2ba60767-78bd-4673-9115-a09ed4a91b6d.png)

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/64x64/apps/gargoyle-house.svg

**Comment by cspiegel** [comment]
Wow, that does a great job of capturing the style of the original.  Thanks!

I've got a preliminary Flathub repo here, which includes your SVG via a patch: https://github.com/cspiegel/flathub/tree/gargoyle

There are some differences in permissions between what you have and what I have.  I'm not too familiar with Flatpak, so if you don't mind, just a few notes here:

* You have `socket=fallback-x11` which looks like it prefers Wayland to X11, if it's available, falling back only in case it's not. That seems reasonable to me, if I understand right.
* I have `socket=pulseaudio`, which is needed for sound support
* I have `device=dri`, which on its face seems unnecessary (Gargoyle doesn't use OpenGL), but Qt does seem to want to do OpenGL rendering. Without this, I can see the following at the terminal:
```
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: MESA-LOADER: failed to open amdgpu: /usr/lib/x86_64-linux-gnu/GL/default/lib/dri/amdgpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/GL/default/lib/dri)
libGL error: failed to load driver: amdgpu
libGL error: failed to open /dev/dri/card0: No such file or directory
libGL error: failed to load driver: radeonsi
```
* I also have `socket=system-bus`, which again isn't needed for Gargoyle itself, but is used at least by the Qt file picker (via Plasma) to talk to UDisks. Without it:
```
kf.solid.backends.udisks2: Failed enumerating UDisks2 objects: "org.freedesktop.DBus.Error.Disconnected" 
 "Not connected to D-Bus server"
```
* I have `filesystem=host`. When I remove this, I can still load files either through the file picker, or on the command line. I can load files from various places, not just $HOME.  I don't understand how Flatpak sandboxing works. Without a filesystem specification, I can still access various files.  It looks like I don't have _full_ access, but a number of things are mounted/bind mounted into the Flatpak dir?  And apparently I have write access to $HOME, at least, so save files work.  Ultimately, things feel like they just magically work with no special filesystem permissions, so it's probably fine, but I don't like not understanding it.

And one thing is still missing, from what I can tell, before this can be accepted to Flathub: an AppData file.  This probably isn't going to be too difficult to create, but will require a license audit.  There are several different interpreters under several difference licenses, which I'll need to double check the licenses of.  Font licenses too.  There's a list of licenses in the Gargoyle source, but it'll be worth verifying that it's up to date.  So we're close to Flatpak, just a bit more work to do.

Thanks again for the icon, I'll get this into the main repo here shortly, so future releases won't need to be patched on Flathub.

**Comment by Aman9das** [comment]
Ok don't worry no patching needed, see https://github.com/flathub/com.remnantsoftheprecursors.ROTP (the flatpak i maintain) to see how to attach icons

About permission, flatpak devs will tell us what permission to use: https://github.com/flathub/flathub/pull/2825

filesystem=host is definitely not acceptable nor necessary

About licence, its gpl, just the code. In ROTP too we had cc-by-sa-nc-nd art and text and music, they said not necessary to include as you can see in the pr

**Comment by cspiegel** [comment]
> Ok don't worry no patching needed, see https://github.com/flathub/com.remnantsoftheprecursors.ROTP (the flatpak i maintain) to see how to attach icons

Alright, that'll work as a stopgap.  Ultimately I'll put the SVG in the Gargoyle repo and install it properly, but for now it can just be slotted in via `install`.

> About permission, flatpak devs will tell us what permission to use: flathub/flathub#2825

OK, the vetting process looks helpful.  Shouldn't be hard to get things hammered into shape that way.

> About licence, its gpl, just the code. In ROTP too we had cc-by-sa-nc-nd art and text and music, they said not necessary to include as you can see in the pr

There are multiple code licenses in Gargoyle due to the fact that it bundles different interpreters.  It's got GPL-, MIT-, and BSD-licensed code, possibly more. But that's just going to be a matter of going through the various interpreters and finding their licenses.

**Comment by Aman9das** [comment]
Ok we just need to read these: https://docs.flatpak.org/en/latest/conventions.html, https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

**Comment by Aman9das** [comment]
[io.github.garglk.Gargoyle.zip](https://github.com/garglk/garglk/files/8367231/io.github.garglk.Gargoyle.zip)

This has been my progress, filesystem=/home is the only big issue to fix :(
icon and desktop file are placed in proper directory

**Comment by cspiegel** [comment]
Do you have problems when filesystem is _not_ set?  It works fine for me, at least from a cursory check.  But again, I'm not overly familiar with how Flatpak operates, so I may be missing something.

Gargoyle already comes with a desktop file, which is more fleshed out than the one included here.  It looks like this:

```
[Desktop Entry]
Version=1.0
Type=Application
Name=Gargoyle
GenericName=Interactive Fiction interpreter
Comment=Interactive Fiction multi-interpreter that supports all major IF formats
Icon=gargoyle-house
Exec=gargoyle %f
Categories=Game;
MimeType=application/x-adrift;application/x-advsys;application/x-agt;application/x-alan-adventure-game;application/x-alan3-adventure-game;application/x-blorb;application/x-glulx;application/x-hugo;application/x-level9;application/x-magscroll;application/x-tads;application/x-t3vm-image;application/x-zmachine;
```
When the new icon is added to the Gargoyle repo here, I think it's probably fine to switch the icon name to `io.github.garglk.Gargoyle` and the desktop file to `io.github.garglk.Gargoyle.desktop`, to better conform to modern freedesktop standards. That'd require patching existing code right now, so if you want to just use a separately-included desktop file as a stop-gap, that's fine, but it ought to merge the keys from the existing desktop file, so the name/description are right and so that there's proper MIME support.  The %f is important too, because it indicates Gargoyle _only_ accepts single files, not multiple files, or URLs.

**Comment by cspiegel** [comment]
> One slight issue that needs patching, or updating: see https://docs.flatpak.org/en/latest/portals-qt.html and
> 
> https://github.com/garglk/garglk/blob/ec39f1a049f8fdba5d4590aa2206dfc6beca6f12/garglk/launchqt.cpp#L114
> 
> are these compatible? relevant issue: [flathub/flathub#1410](https://github.com/flathub/flathub/issues/1410)

The relevant part:

> Use `QFileDialog` class to open files. Avoid using `QFileDialog::DontUseNativeDialog`. Note that portals cannot currently give access to directories on the host filesystem

So Gargoyle _is_ using `QFileDialog`.  Very confusingly, though, the `-DWITH_NATIVE_FILE_DIALOGS=OFF` CMake option explicitly sets `QFileDialog::DontUseNativeDialog`, directly contradicting this advice.  That's because, when I've tested, avoiding `QFileDialog::DontUseNativeDialog` prevents files from being able to be opened.  I added this option to support Flatpak, as a matter of fact.

Which is to say, my experience is the opposite of the advice given.  Native file dialogs fail, Qt dialogs succeed.  I have absolutely no idea why.

**Comment by Aman9das** [comment]
I feel its best to create a pr now, the flatpak devs are very helpful at ironing things out. At worst we would access /home, not a big issue.

**Comment by cibersheep** [comment]
I have a suggestion. What do you think going into this route?

![noun-gargoyle-1974749-mod](https://user-images.githubusercontent.com/6640041/160724933-59f972f9-790e-4179-8c93-82f6c8449ff6.svg)

Original svg is CC-By [Grégory Montigny](https://thenounproject.com/icon/gargoyle-1974749/)

**Comment by Aman9das** [comment]
Changing the branding without actual drastic change in the product is not a good idea. Also app icon has to  take up substantial portion of the squarish alloted region, that is why no app icon is a triangle..

https://developer.gnome.org/hig/guidelines/app-icons.html gnome hig gives a handy set of rules to app icon design

**Comment by cibersheep** [comment]
> [...] that is why no app icon is a triangle.. it should not be too narrow or wide.
It is not triangular, is a diamond-shape :)


> And the gargoyle-house branding is very strong, I am non native speaker, so did not know of traditional gargoyles. "Gargoyle" meant the interactive fiction interpreter to me. Just like you generally think of Amazon, the company over the rainforest.

I would say all Latin languages and English has French word as origin. To me, first time I saw the house icon was puzzling. Still today, I don't know why a house for a glk Gargoyle app (glk reminds me to «gelek», «a lot of them» in Kurdish). But I'm losing the point here...
 
> But the gargoyle art is very well-made indeed!

Thank you

Obviously there is no obligation to use any of these icons (nor keep them like they are), you can just ignore them, no bad feelings. I just had time and I was in the mood to create them :D so...

**Comment by cspiegel** [comment]
The house is a reference to Zork:

> You are standing in an open field west of a white house, with a boarded front door.

It makes sense from an "insider knowledge" perspective, and Gargoyle is the type of niche project where I'd expect a large portion of its potential users to understand the reference, though this may be a smaller percentage than when it was initially introduced.  I'm not sure when that was: very possibly from the inception of the project.  At least the first Subversion commit by Ben Cressey in 2008 had the Windows icon, and it's not unlikely that Tor Andersson included it in his first release.

That being said, Tor's original [Gargoyle site](http://ccxvii.net/gargoyle/) has Gargoyle imagery, so it's not unprecedented for the project to have a literal Gargoyle associated with it.  I think the white house, while a nice nod to Infocom and interactive fiction in general, is probably not a great representation of the project.  In a vacuum, I think an actual gargoyle is better, as it at least has a direct tie to the name, if not the nature, of the program, especially given that "white house" isn't really a direct representation of interactive fiction anyway.

I don't know how much it matters that Gargoyle has over 15 years of a house icon.  It's not as though "branding" matters much.  I don't think many Gargoyle users are going to decide that an icon change is just too much to bear.

**Comment by cibersheep** [comment]
> The house is a reference to Zork:
> 
> > You are standing in an open field west of a white house, with a boarded front door.

Oh! Thanks. Now it is obvious (and now I feel a bit silly :D)
 
> That being said, Tor's original [Gargoyle site](http://ccxvii.net/gargoyle/) has Gargoyle imagery, so it's not unprecedented for the project to have a literal Gargoyle associated with it. 

And I realised that the program was called garglk in the earlier releases as well.

>I think the white house, [...], is probably not a great representation of the project. [...]I think an actual gargoyle is better, as it at least has a direct tie to the name, if not the nature, of the program [...]

I'll be happy with whatever decision you make. You can ping me if you need changes to the gargoyle proposal, you need a house icon or you have any suggestions.

**Comment by Aman9das** [comment]
Hi, the original aim of the issue was to request flatpak publication. Is there something more I could do to help out?

**Comment by cspiegel** [comment]
> Hi, the original aim of the issue was to request flatpak publication. Is there something more I could do to help out?

At this point I'm just going to get the main repo up to date with fd.o standards, and at that point I'll probably be in place to submit a pull request to flathub (with some patches/updates from the master branch).

As to icons, for the 2022.1 release I'll use the house SVG since it's in line with the existing 2022.1 packages. Whether it's a good idea to switch away to a different "branding" is worth thinking about for the next release.  Right now I'm not sure what the best thing to do is.

**Comment by cspiegel** [comment]
@Aman9das I have an almost-ready repo here: https://github.com/cspiegel/flathub/tree/gargoyle

One problem I have is that, in Plasma, the icon isn't showing up in my launcher.  As far as I can tell the path is right and the desktop file is right.  If you want to take a look, maybe you can see what's wrong with it, if indeed anything is.

**Comment by Aman9das** [comment]
Its perfectly good in gnome and xfce, and the files are placed correctly. It may be a plasma bug, will probably be fixed after restart.

How does `--filesystem=xdg-documents:~/Games` sound to you?

**Comment by cspiegel** [comment]
Gargoyle probably should have full home directory access: I don't want to restrict where people can put their games, but it shouldn't need anything beyond that.  I've updated it to specify `--filesystem=home`.

**Comment by Aman9das** [comment]
filesystem=home is very good.

But I think it'd be good if we ask in the forums where people generally place their interactive fiction files. After a month, we would know if there is a common trend or not.

Then we can update the filesystem permission if most people use a certain folder. Of course some people would use external storage or other folders. Flatseal could be used for those, right?

**Comment by Aman9das** [comment]
```
<?xml version='1.0' encoding='utf-8'?>
<component type="desktop-application">
    <id>io.github.garglk.Gargoyle</id>
    <metadata_license>FSFAP</metadata_license>
    
    <name>Gargoyle</name>
    <summary>An Interactive Fiction Player</summary>
    <description>
        <p>
             Gargoyle is an IF player that supports all the major interactive fiction formats.
        </p>
        <p>
        	Most interactive fiction is distributed as portable game files. These portable game files come in many formats. In the past, you used to have to download a separate player (interpreter) for each format of IF you wanted to play.
        </p>
        <p>
        	Gargoyle supports Agility, Alan 2 and 3, Frotz (glk port), Glulxe, Hugo, Level 9, Magnetic, Scare and Tads 2/3 games.
        </p>
    </description>
    
    <screenshots>
    	<screenshot type="default">
    		<image>https://ccxvii.net/gargoyle/shots/tads-lcd.png</image>
    	</screenshot>
    	<screenshot>
      		<image>https://ccxvii.net/gargoyle/shots/glulx1.jpg</image>
    	</screenshot>
    	<screenshot>
      		<image>https://ccxvii.net/gargoyle/shots/glulx2.png</image>
    	</screenshot>
    	<screenshot>
      		<image>https://ccxvii.net/gargoyle/shots/level9.jpg</image>
    	</screenshot>
    	<screenshot>
      		<image>https://ccxvii.net/gargoyle/shots/magnetic.jpg</image>
    	</screenshot>
  	</screenshots>
    <categories>
        <category>Game</category>
    </categories>
    
    <url type="homepage">https://github.com/garglk/garglk</url>
    <url type="bugtracker">https://github.com/garglk/garglk/issues</url>
    <launchable type="desktop-id">io.github.garglk.Gargoyle.desktop</launchable>
    
    <releases>
        <release version="2022.1" date="2022-01-30"/>
        <release version="2019.1.1" date="2019-11-19"/>
        <release version="2019.1" date="2019-11-03"/>
        <release version="2011.1" date="2011-10-19"/>
    </releases>
    
    <provides>
        <binary>gargoyle</binary>
    </provides>
    
    <project_license>Artistic-2.0 AND BSD-2-Clause AND BSD-3-Clause AND GPL-2.0-only AND GPL-3.0-only AND MIT</project_license>
    
</component>
```

**Comment by cspiegel** [comment]
Tor's original site (at ccxvii.net) is out of date; the interpreter list isn't quite right anymore, but I can fix that easily enough.

The screenshots will have to be copied here into the asstes repository (https://github.com/garglk/assets) so we don't send traffic to his site, but I think I'll want to recreate them, since half are JPEG, which is subpar.  Though I just discovered a graphics glitch in Photopia that was apparently introduced some time in the last 15 years... oops.  At any rate, I can take a few screenshots of modern, representative games, and put them in the assets repository.

**Comment by Aman9das** [comment]
> Tor's original site (at ccxvii.net) is out of date; the interpreter list isn't quite right anymore, but I can fix that easily enough.
> 
> The screenshots will have to be copied here into the asstes repository ([garglk/assets](https://github.com/garglk/assets)) so we don't send traffic to his site, but I think I'll want to recreate them, since half are JPEG, which is subpar. Though I just discovered a graphics glitch in Photopia that was apparently introduced some time in the last 15 years... oops. At any rate, I can take a few screenshots of modern, representative games, and put them in the assets repository.

Ok I highly recommend following this: https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

very nice instructions for taking screenshots!

**Comment by cspiegel** [comment]
Alright, I've updated the appdata and taken a few new screenshots.  No Photopia due to the graphics glitches.  I'll have to do a bisect at some point to figure out where it went wrong.

**Comment by cspiegel** [comment]
Aaand, Photopia screenshot added.  I went back as far as the 2010 release which shows the same issues; but they can be mitigated by resizing the window.  Windows Git exhibits the same behavior, so it's probably a bug in Photopia's assumptions about window sizes.

**Comment by Aman9das** [comment]
Looking really nice :)

And filesystem not needed! Then we are ready to go!

**Comment by cspiegel** [comment]
Unfortunately not all file access is done through portals.  Config files, for example, are loaded with normal C or C++ I/O routines.  That means you can't edit your config files locally and expect them to work in the Flatpak version.  This isn't the worst thing in the world (though quite annoying), but the next problem is a deal breaker: some games (Z-machine and Glulx typically) can package resources in a separate file (a Blorb file).  This isn't loaded via the portals, but again with standard I/O routines.  If I build without `--filesystem=home`, then, as an example, Infocom's Sherlock has no sound, because the Blorb file can't be found.

If Flathub rejects `--filesystem=home` we'll have to be more granular, such as with XDG documents, but that'll provide an inferior experience.

**Comment by Aman9das** [comment]
They will not mind, since there is legitimate issue.

In the future there are plans to let portals give access to related files too. Like opening local index.html will also give access to the rest of the necessary css files

**Comment by Aman9das** [comment]
I talked to the admins about this, there is already work going on about this: https://github.com/flatpak/xdg-desktop-portal/issues/463

they recommend --filesystem=home so we are good. Later we can improve the filesystem access if the portals api improves

**Comment by cspiegel** [comment]
Alright, got a pull request open at flathub/flathub#3022.

**Comment by Aman9das** [comment]
I have created a pull request as per https://github.com/flathub/flathub/pull/3022#discussion_r851672010

He meant to install the files through manifest and not patching the archive

**Comment by cspiegel** [comment]
Ok, looks like we're up and running now: https://flathub.org/apps/details/io.github.garglk.Gargoyle

Thanks for pushing me to get this finished.

**Comment by Aman9das** [comment]
I couldn't be happier, gargoyle raised me for 5 years of my childhood, practically. Thanks for making a medium of entertainment easily accesible.
