### ISSUE TITLE
Respond to Dark Style Preference

### ISSUE THREAD

**Issue by Aman9das** [garglk/garglk#642]
All the major platforms now allow the user to set their dark-style preference. Most of them also let the developers opt-in to follow the user-set preferences.

Thus it would be nice if Gargoyle would follow the respective platform's specifications. It has the advantage of following arbitrary changes to the user's preferences without the user having to manually change the config. Also allowing day-night scheduling if made available by the platform.

Cassidy James makes a convincing argument in favor of a Dark Style Preference, and highlights what the major Platforms offer: https://blog.elementary.io/the-need-for-a-freedesktop-dark-style-preference/ (Note: freedesktop has indeed caught up since the article was published)

**Comment by cspiegel** [comment]
See also #345.  There will probably need to be some new "theme" config option which overrides individual settings, with hard coded dark and light themes (plus a pseudo system theme), as well as user-settable themes.

**Comment by cspiegel** [comment]
I have some early work done on this.  If you'd like to try it and give feedback, there are builds here:

[Linux (x86_64 AppImage)](https://nightly.link/cspiegel/garglk/actions/runs/2634466314)
[Windows (all)](https://nightly.link/cspiegel/garglk/actions/runs/2634466298)
[Mac (unsigned Intel disk image)](https://nightly.link/cspiegel/garglk/actions/runs/2634466299)

You need to edit your config file, and _after_ all the existing color options, put this:

```
theme system
```
This will attempt to follow the system color theme.  It also supports "light" and "dark" directly.

**Comment by cspiegel** [comment]
This plus custom themes are now in pull request #664, and should make it into the next major release.
