### ISSUE TITLE
Where to place/find  .garglkrc? (Debian Linux)

### ISSUE THREAD

**Issue by jason-mehmel** [garglk/garglk#685]
Hi there!

After seeing an old post on Reddit about changing the colour themes of Gargoyle, I started looking for the  .garglkrc file, but can't find it anywhere.

Where should I be looking?

And if I was going to generate my own, where would I put that? Where is the program looking for the config file?

**Comment by jason-mehmel** [comment]
Never mind! Found the /etc/garglk.ini file, and from there was able to see that I can put the .garglkrc in the right places.

**Comment by jason-mehmel** [comment]
Great question re: documentation...

It might be worth a note right on the readme page, even if just to point to its general locations in most installations, or a readme/config doc, if you want to contain the information away from the general readme section.

I know I was scanning the readme section to try to find what I could. Then I checked the Themes folder in the github file listing.

The chances of anyone downloading a text adventure player AND wanting to tweak it are high, in my opinion, so letting them know where that is right up front is probably a good idea!

Thanks for engaging with me on this!

**Comment by fourier** [comment]
I had exactly the same problem, and only found the config file name by googling and finding this exact issue here. I suggest to add "Configuration" section to the documentation, providing the file names and paths to the configuration file on all platforms, as well as listing all available options with their documentation, possible values and default values.

Additionally `gargoyle` command  doesn't support the --help argument nor provides information about config file.
It even doesn't have a `man` page, which would be another way to find out about location of the config file and its format.

**Comment by cspiegel** [comment]
> It might be worth a note right on the readme page, even if just to point to its general locations in most installations, or a readme/config doc, if you want to contain the information away from the general readme section.

> I know I was scanning the readme section to try to find what I could. Then I checked the Themes folder in the github file listing.

> The chances of anyone downloading a text adventure player AND wanting to tweak it are high, in my opinion, so letting them know where that is right up front is probably a good idea!

For users that come to Gargoyle via its Github page, this would certainly be a benefit.  I'll do my best to find time to write up a wiki page that can be linked from the README, so there's at least some semblance of documentation for new users.

>I had exactly the same problem, and only found the config file name by googling and finding this exact issue here. I suggest to add "Configuration" section to the documentation, providing the file names and paths to the configuration file on all platforms, as well as listing all available options with their documentation, possible values and default values.

> Additionally gargoyle command doesn't support the --help argument nor provides information about config file.
It even doesn't have a man page, which would be another way to find out about location of the config file and its format.

I've written up a basic man page in #687.  Critique away!  I can add a `--help` flag, for sure.  There's not a whole lot of options for Gargoyle, but at the very least it can print out where to find the config file, for example, and point to the wiki page if nothing else.  Incidentally, to find paths while running Gargoyle, use control-period.  That'll show the config and theme paths (only available on master right now).

There's certainly a discovery problem.  Gargoyle is a get-out-of-your-way interpreter, which means no distractions, even menu/toolbars. But that also means that you have no clue what to do if you just open it!  As noted, there are a few avenues users might go to glean information about Gargoyle, and I'll see if I can't shore that up soon.  I have to get a new release out shortly to accommodate upcoming changes in Inform next year, but it shouldn't be hard to get the man page and `--help` output done.  The wiki can be updated even after the release, of course.

One "obvious" thing would be to have F1 pop up a help dialog, but that's not possible: Glk (which Gargoyle implements) allows interpreters to receive function keys, so I can't hijack them (I _could_ hijack F1 if the current interpreter hasn't asked for it, but I don't like that inconsistency).

I'm not the original author of Gargoyle (maintenance kind of fell in my lap a while back), but I am a long time user/developer, and given my intimate acquaintance with it, it's sometimes hard for me to see things from the perspective of new users.  I appreciate the feedback here!  Changes may be slow, but they'll be coming.

**Comment by cspiegel** [comment]
I've added a configuration section to the README, in #707.

Gargoyle also now supports various command-line options.  Editing configuration files should, hopefully, be somewhat easier and a bit more discoverable now, even if only through the Github landing page.

**Comment by fourier** [comment]
Thanks a lot and Happy New Year! :)

**Comment by cspiegel** [comment]
Closing due to the merged #707.
