### ISSUE TITLE
Suggestion: Update AGiliTy to 1.1.2

### ISSUE THREAD

**Issue by bjbest60** [garglk/garglk#696]
AGiliTy 1.1.2 was released in March 2022.  Certain games (I think produced with the AGT Master's Edition) using ver. 1.1.1 produce "GAME ERROR: Invalid argument to metacommand token." very frequently, making the game unplayable. Ver. 1.1.2 seems to solve that particular issue, at least for the games I've tried.

**Comment by cspiegel** [comment]
Thanks for the pointer!  #697 contains the update.  If there are no problems, I'll merge it in shortly.

If you have a pointer to a problematic game, I can give it a test before merging.

**Comment by cspiegel** [comment]
Updated.
