### ISSUE TITLE
Text rendering problems in 2023.1 RC

### ISSUE THREAD

**Issue by Nephar** [garglk/garglk#729]
I have encountered a grid window rendering issue for z-code, while I was testing Slag hint system from ifarchive.org (Mojave). Possibly due to the new version of Bocfel.

2023.1 RC renders the file like this:

<img width="720" alt="Screen Shot 2023-01-14 at 17 59 19" src="https://user-images.githubusercontent.com/122389007/212478969-8e3d20ba-4458-482a-b6dc-000235dbbc8c.png">
 
Garglk 2022.1, Lectrote 1.4.3, and Spatterlight 0.9.8 respectively with the same file:
<img width="720" alt="Screen Shot 2023-01-14 at 18 00 45" src="https://user-images.githubusercontent.com/122389007/212479168-2509fa35-7e49-4f7b-bd39-78ea05c0842b.png">
<img width="882" alt="Screen Shot 2023-01-14 at 18 01 25" src="https://user-images.githubusercontent.com/122389007/212479187-5dd720ed-c1a8-496f-b402-0fbd39ba15d1.png">
<img width="729" alt="Screen Shot 2023-01-14 at 18 02 04" src="https://user-images.githubusercontent.com/122389007/212479301-aefd1dbd-06d4-4176-a979-50c965003e1e.png">

The offending file, compiled by **Inform 6.34 for MacOS (21st May 2020)**, is [this one](https://drive.google.com/file/d/1pRU4nsbOGIqsauHdly0ZySEY0jZMcpta/view?usp=share_link). And the source is [like this](https://drive.google.com/file/d/1CMESDUCyphdJABuNeG0M0DvfRJuNv1q8/view?usp=share_link).

Edit: Typo.

**Comment by cspiegel** [comment]
Good find, thank you!  I tracked this down and it should now be fixed in 726134e88dfe62f4074e5513f7e66b0d8605cea2.
