### ISSUE TITLE
Changed code signature in macOS 2023.1 download?

### ISSUE THREAD

**Issue by suschizu** [garglk/garglk#747]
Hello there - I've noticed that the code signature has changed in the latest release - can you confirm it? thanks 
(https://github.com/garglk/garglk/releases/download/2023.1/gargoyle-2023.1-mac-x64.dmg)
EXPECTED Andrew Plotkin (BK75QRDQ9E) 
FOUND Petter Sjolund (6U7YY3724Y)

**Comment by angstsmurf** [comment]
Possible duplicate of #611?

**Comment by cspiegel** [comment]
Yep, same issue as #611.  This is the expected behavior.

And, for that matter, the signature on Intel builds will be different in 2023.1 as well.  Now it is:

Christopher Spiegel (NUDUJJ3WVP)

**Comment by angstsmurf** [comment]
I wonder if this is a bot of some kind.

**Comment by suschizu** [comment]
no I'm not a bot :)
sorry for that - I just received the same error in my update log again - just fixed it
