### ISSUE TITLE
Feature Request: Plain text viewing

### ISSUE THREAD

**Issue by za3k** [garglk/garglk#800]
Gargoyle's typography is miles ahead of anything else I've encountered.

Is it possible it could support viewing plain-text or epub files? I would be quite happy with just .txt, especially if I could call it from the command line: `gargoyle abc.txt`

**Comment by za3k** [comment]
nvm, found mupdf by the same author, this is a silly requsat given that exists.

**Comment by salty-horse** [comment]
ePub would be tricky, as Gargoyle doesn't have any way of showing web pages.
