### ISSUE TITLE
Include source archive in release assets

### ISSUE THREAD

**Issue by blabber** [garglk/garglk#855]
The source download on the release page is based on GitHubs "on-the-fly" archives (powered by `git-archive`). In the blog post ["Update on the future stability of source code archives and hashes"](https://github.blog/open-source/git/update-on-the-future-stability-of-source-code-archives-and-hashes/) GitHub have announced on 2023-02-21 that source downloads will be stable for a year.

This is obviously still working today, but please consider putting self rolled archives in the release assets to be safe in the future.

**Comment by cspiegel** [comment]
Thanks for the pointer; I'll create new archives for existing releases and include them in new release.

I always kind of disliked that the name of the tarball was "garglk" anyway, so now it's a good excuse to make the "official" release tarball with a "gargoyle" name.

I'll close this once I've got past release done.

**Comment by cspiegel** [comment]
OK, I've updated previous releases with tarballs and will do so for future releases as well.
