### ISSUE TITLE
Journey: Weird repeated word in some versions

### ISSUE THREAD

**Issue by angstsmurf** [garglk/garglk#870]
This is weird: Having Praxix examine his pouch (which can be done on the first turn of the game) will repeat the word "essence":

> He did so now, taking out his pouch and finding a large amount  of air essence essence (enough for seven or eight spells), and a  very large amount of earth essence essence (enough for nearly ten spells).

This does not happen in the original interpreters, in Frotz, or in releases of the game earlier than 51.

EDIT: It seems to have something to do with screen width. If I make the window wide enough, it won't reproduce. I guess the culprit is [this code ](https://github.com/the-infocom-files/journey/blob/1b689ae9ec8808304a24ab57644d052160c409f5/spells.zil#L168-L189)in `SPELLS.ZIL`, `ROUTINE TELL-AMOUNTS`, which only triggers if the screen is less than `12-WIDTH` (a constant value of 71):
```
<TELL " amount of ">
		   <TELL D .F>
		   <COND (<AND <L? ,SCREEN-WIDTH ,12-WIDTH>
			       <NOT <EQUAL? .OBJ ,REAGENTS>>>
			  <TELL " essence">)>
```

EDIT 2: Apparently [a change was made in release 51](https://github.com/the-infocom-files/journey/blob/1b689ae9ec8808304a24ab57644d052160c409f5/output.zil#L381-L390) to always use full object description (the `SDESC` property) when not printing to the "command area" (and thus the `CMD` flag argument to the `PRINT-DESC` routine is false.) The full descriptions of the essences contain the word "essence", while the shorter variants don't.
```
;"Always print full name if not in command area..."
		<PRINT <GETP .OBJ ,P?SDESC>>)
	       (T
		<PRINT <GET-DESC .OBJ>>)>>
```
Simply NOPing out the ` <TELL " essence">` line in `TELL-AMOUNTS` in version 51 and later should be enough to fix this, as `TELL-AMOUNTS` is only called when examining the pouch.

**Comment by angstsmurf** [comment]
I just checked the Apple II release available from the Internet Archive, which is release 77, and the bug occurs there. That is probably the only original Infocom interpreter that uses a screen width of less than 71 characters.

I don't know about the other official releases, but the ones I have seen are Mac OS release 26, Amiga release 30, and MS-DOS release 83.

**Comment by cspiegel** [comment]
Alright, I just decided to patch all versions 51 and above.  I'm attaching the patch here.  This'll be in the next Bocfel release but you can either patch manually or add to a patch file, if/when that is implemented in Spatterlight.

Maybe I set a record for the number of times the word "essence" appears in a single comment.

[essence.txt](https://github.com/user-attachments/files/16857947/essence.txt)

**Comment by angstsmurf** [comment]
Thanks! I suppose this issue can be closed now.

**Comment by cspiegel** [comment]
OK, merged in the patch here, and I've got it locally in Bocfel, so whenever a new release comes out, it'll be fixed there, as well.

Thanks for figuring this out.
