### ISSUE TITLE
License questions/issues

### ISSUE THREAD

**Issue by autumnontape** [garglk/garglk#894]
Which version of the GPL is garglk itself under? License.txt only says "It is released under the terms of the GNU General Public License." As silly as this is, I'm interested in this because I'm making a split Arch User Repository package that will only contain `garglk/gargoyle-docu2.png` and I'd like to know the license for that file; this is to fix a conflict with the QTads package, since it also wants to provide icons for application/x-tads and application/x-t3vm-image.

**Comment by cspiegel** [comment]
The code itself is GPLv2 or later (check the top of each source file).

It's reasonable to assume the images would be under the same license, although as I'm not the original author, I can't say with complete certainty.

The images go back at least as far as version 2006-09-17, released by Tor Andersson, the original author. So ultimately he's the one who _knows_ what the license is; but as the rest of Gargoyle itself is GPLv2+, the images are likely to be as well.

**Comment by autumnontape** [comment]
Thank you!!

**Comment by autumnontape** [comment]
Licenses aren't such a big deal in the AUR because you're not actually distributing anything but the build script there, but I'm thinking of packaging Gargoyle for a binary distribution now and taking a closer look at the license situation. The main thing I've found is that there seems to be code here under incompatible versions of the GPL (v2-only and v3-only).

These components use GPL v2 or higher, or GPL v2 or v3 in the case of bocfel, and are okay:

* garglk
* level9
* magnetic
* scott
* bocfel

These components use GPL v2 only:

* agility
* jacl
* scare
* tads
* taylor

And these components use GPL v3 only, as far as I can tell:

* plus
* xbrz

I've gathered that the "plus" interpreter is under GPL v3 only, because it seems to come from Spatterlight, which is under that license. That also seems like a problem for Spatterlight, since it includes all of the same GPL v2 only interpreters as Gargoyle. But it could be that there's something that isn't clear to me.

The other possible licensing issue I found is that the MIT license for Adrian Welcker's FrankenDrift code isn't in the repo.

License.txt could also use updating, and it would be nice for it to include the different version numbers of the GPL the different components are available under. I can submit a pull request doing both if you'd like.

**Comment by angstsmurf** [comment]
> I've gathered that the "plus" interpreter is under GPL v3 only, because it seems to come from Spatterlight, which is under that license.

The Plus interpreter is not really "taken from" Spatterlight, it is more like developed by me in parallel for both Spatterlight and Gargoyle, and I never gave any thought to which license it is released, except that it is has to be that is compatible with Gargoyle.

To be honest, I never gave any thought to which license Spatterlight should have either. I simply kept the one used when the Spatterlight source was uploaded to Github by some guy (Juande Santander-Vela) who is not the original author. I suspect he didn't give it much thought either, as the original source was released under GPL before v3 was a thing. I kind of assumed that if there was a problem with this, somebody would tell me.

**Comment by autumnontape** [comment]
> > I've gathered that the "plus" interpreter is under GPL v3 only, because it seems to come from Spatterlight, which is under that license.
> 
> The Plus interpreter is not really "taken from" Spatterlight, it is more like developed by me in parallel for both Spatterlight and Gargoyle, and I never gave any thought to which license it is released, except that it is has to be that is compatible with Gargoyle.
> 
> To be honest, I never gave any thought to which license Spatterlight should have either. I simply kept the one used when the Spatterlight source was uploaded to Github by some guy (Juande Santander-Vela) who is not the original author. I suspect he didn't give it much thought either, as the original source was released under GPL before v3 was a thing. I kind of assumed that if there was a problem with this, somebody would tell me.

@angstsmurf Then it sounds like Tor Andersson intended to place his code under GPL v2 and any later contributors intended to place their code under GPL v3. I don't know if Juande himself has any code in there. None of [the commits GitHub attributes to him](https://github.com/angstsmurf/spatterlight/commits?author=juandesant) include code changes.

Given that your version of UNP64 includes changes under GPL v3 from ScummVM... as I'm now realizing Gargoyle's does, too... I think the best way to resolve any GPL conflicts, assuming you want to, would be to get a hold of each person who has code in Spatterlight and get a GPL v2/v3 or v2+ license for it from them. There only seem to be a few people who have committed to the repository, so that seems pretty tractable.

**Comment by cspiegel** [comment]
Realizing that the GPLv3 thing is going to be a problem for _everbody_ who distributes Gargoyle, I've got a pull request at #900 for consideration, which disables xBRZ by default, building it only if you do `-DENABLE_GPL3=ON`.

This is not a full solution, but will at least help either with the bifurcated interpreter solution I noted above, or allow you to just disable xBRZ entirely while still supporting the hqx scaler.

**Comment by angstsmurf** [comment]
Just to clarify, UNP64 has a Zlib license. We were granted permission by the original authors to relicense it.

**Comment by awlck** [comment]
> Looks like there's a 3-clause BSD license from the original Adrift code; is there a separate FrankenDrift license we're missing that you could add?

Yes, the Adrift code is under a 3-clause BSD license, my frontend code is MIT licensed. (In retrospect, I'm not sure why I thought it would be a good idea to have two licenses involved there, even if they're similar.)

(For the record: a binary distribution of FrankenDrift would likely also have to consider [the .NET runtime's own license](https://github.com/dotnet/runtime/blob/main/LICENSE.TXT) (MIT).)

**Comment by cspiegel** [comment]
> Yes, the Adrift code is under a 3-clause BSD license, my frontend code is MIT licensed. (In retrospect, I'm not sure why I thought it would be a good idea to have two licenses involved there, even if they're similar.)

Do you mind adding license info for your pieces to your #899 pull request?  Just enough info to make clear that there are two licenses for the FrankenDrift stuff, and that yours is MIT.

**Comment by cspiegel** [comment]
This should be fixed in #901. If there are any more license questions/issues, don't hesitate to bring them up.
